### ISSUE TITLE
Converting ECEF to Unity worldspace?

### ISSUE THREAD

**Issue by gnistregn** [wrld3d/unity-api#10]
So I've been poking around, trying to convert (WGS84) coordinates into something that projects a gameObject properly onto a Wrld map using the ECEF world space, but frankly I'm quite stumped at this point. I guess I need to take into account the current projection/position of the camera, but maybe there's some undocumented stuff in there that would aid me in not reinventing the wheel..? Would be grateful for any help/pointers on this!

**Comment by tim-jenks** [comment]
@gnistregn - https://docs.eegeo.com/unity/latest/docs/types/Wrld.Space.LatLongAltitude/ allows you to convert to & from WGS84 lat,lon plus altitude (where altitude is AMSL, above mean sea level).

Specifically the FromECEF & ToECEF provide the conversions you are looking for.

There is also a helper type EcefTangentBasis that allows you to position and orient entities on the surface of the earth https://docs.eegeo.com/unity/latest/docs/types/Wrld.Common.Maths.EcefTangentBasis/

It's worth noting, if you're wanting to just use Unity like you normally use Unity - and work in a local area of the world - you may find the UnityWorldSpace much more familiar to work in!

**Comment by gnistregn** [comment]
@tim-jenks Thanks for your reply! I think I might have been unclear about what I'm trying to achieve. I have no trouble converting WGS84 to ECEF. What I'm struggling with is using the ECEF to project a Unity transform in the right position, given the current camera position etc. Basically, I want to place markers and draw stuff in relation to the map as the user pans around it. (Using the built-in camera controls)
I could use UnityWorldSpace, but the ECEF worldspace is a more fun challenge :)
