### ISSUE TITLE
Add api to obtain notification of initial map load completion

### ISSUE THREAD

**Issue by jonty-dawson** [wrld3d/unity-api#100]
It would be desirable to have Api to obtain notification once all streamed resources for an initial scene / camera point of view have loaded. This would allow developers to e.g. show a loading screen if desired while initial map tile resources streamed in.

**Comment by ArslanJafri** [comment]
`OnInitialStreamingComplete` is available in v0.8.17 and onwards.
See: https://www.wrld3d.com/unity/latest/docs/types/Wrld.Api/
