### ISSUE TITLE
Still no Unity Wrld SDK on the asset store

### ISSUE THREAD

**Issue by Rakiah** [wrld3d/unity-api#102]
Hello,

we still have no SDK on the store for a long time now (and no update since we have 0.7 for multiple months)

Is the Unity WRLD SDK dead ?

**Comment by Rakiah** [comment]
Apparently yes
If you're wondering if you should pick WRLD as your mapping solution, don't

**Comment by olivernorton** [comment]
We're currently working with Unity to improve the way we offer the WRLD Unity SDK through the Asset Store.

We're committed to supporting the WRLD Unity SDK and you'll always be able to download the latest version from our website here https://wrld3d.com/unity/latest/docs/examples/

We'll let you know as soon as we're back on Asset Store.
