### ISSUE TITLE
Can i Import my building into wrld?

### ISSUE THREAD

**Issue by hieub1509861** [wrld3d/unity-api#105]
### Description

I was make a indoor map (a building).But i dont know how to used it like Examples.unity
(EnterMap/exitmap.......)
How to add my indoormap into Wrld?
Thanks!

**Comment by ghost** [comment]
Once you have created and submitted a valid indoor map to WRLD (following the steps here: https://github.com/wrld3d/wrld-indoor-maps-api/blob/master/TUTORIAL-TOOL.md) to make it available in your Unity app you need to use a Coverage Tree Manifest that includes your indoor map data.  You can either:

1) Use the building preview manifest which you can obtain from the Indoor Map Tool, and pass it as the CoverageTreeManifestUrl in the params when you create the map: https://www.wrld3d.com/unity/latest/docs/types/Wrld.ConfigParams/

2) Submit your map for publication to WRLD, and it will become available in the default public manifest, which is included in the SNAPSHOT version of the Unity SDK: https://docs.wrld3d.com/unity-SNAPSHOT/latest/docs/api/
