### ISSUE TITLE
Does it support the latest version of Unity? i.e 2019?

### ISSUE THREAD

**Issue by dellams** [wrld3d/unity-api#106]
We noticed that you say the Unity SDK supports version's between 2017.3.0f2 and 2018.1.0f2.

Does it support any after that like 2019?

We also noticed you haven't updated the Unity version for a long time, it is still 0.7 from the last time we checked a year ago. We hope you are still actively developing this version?

We also notice a lot of features from the other versions are missing on the Unity one, why is this? Will they be added soon? Is there a roadmap for the Unity version?

Also, are you planning on mapping the whole globe? If so, how long will this take? We REALLY need the whole world mapped ASAP please because Our World is a Pokemon Go Killer, we started designing this 7 years ago long before Pokemon Go came out, which is a very primitive compared to Our World.

**Comment by ghost** [comment]
Hi @dellams, I know you've been in touch via email so just answering here in case other users stumble across the question.

We have released an updated WRLD Unity SDK v0.8 - https://cdn1.eegeo.com/unity/wrld.unity.sdk.0.8.17.release.zip

This supports Unity Editors 2019 and 2020, and has a bunch of additional features that are described here: https://www.wrld3d.com/unity/latest/docs/examples/whats-new-unity-sdk-0.8/

We are increasing our map coverage incrementally - you can see which regions we have covered as well as register a vote to help us prioritise new areas here: https://www.wrld3d.com/3d-maps/mapping-data#WRLD-MAP-COVERAGE
