### ISSUE TITLE
Maping Problem

### ISSUE THREAD

**Issue by redagrandrei** [wrld3d/unity-api#107]
Hello. Doest Wrld supports all the locations from the globe? Cause i cant find my location for example? Seems that WRLD3D has just some cities and thats all. Thats very sad we wanted to use your sdk in our project. But without needed map locations its useless.
Are you planning to update unity sdk anytime soon?

**Comment by ArslanJafri** [comment]
Hi @redagrandrei,
Thanks for your interest in our maps!

While our goal is to have full coverage of Earth, unfortunately we do not currently have all locations available right now. You can see our current coverage and vote for what you would like to see next here:
https://www.wrld3d.com/3d-maps/mapping-data#WRLD-MAP-COVERAGE
We can also expedite the building of an area based on commercial agreements. If you believe that this applies to you, please contact our sales team at enquiries@wrld3d.com.
As for Unity, we are still actively developing and supporting the Unity SDK and will be updating it once development on the new version concludes.

Kind regards,
Ali

**Comment by BrettGregson** [comment]
Czech Republic (50.0755, 14.4378) is covered according to your site but I only get water when using that lat/long

**Comment by ghost** [comment]
@BrettGregson coverage of the Czech Republic was added after the last release of the Unity SDK.  To add you, you can follow the steps in this blog post: https://www.wrld3d.com/blog/wrld-expands-3d-map-coverage-with-46-countries-across-europe/

We'll be releasing a new SDK later this month which supports Unity 2019 and 2020, and has the latest map coverage included.
