### ISSUE TITLE
Current status of WRLD Unity SDK (on Android)

### ISSUE THREAD

**Issue by JustinFincher** [wrld3d/unity-api#108]
Thanks for your time reading this, now as outlined in [developer.android.com](https://developer.android.com/distribute/best-practices/develop/64-bit):
> Starting August 1, 2019, your apps published on Google Play will need to support 64-bit architectures.

The WRLD Unity SDK (v0.7.1019) still does not support 64 bit (only a `armeabi-v7a` aar file in the plugins folder), making it difficult if not impossible for WRLD Unity projects to be published on Google Play.  
I wonder if WRLD Unity SDK is still supported or not? The current status is a little bit confusing, especially considering the recent pricing changes made to WRLD ($16/mo for Unity with no limits in user count) which seems to be a big push on the gaming usage.

**Comment by ghost** [comment]
We are currently working on an update to the WRLD Unity SDK to bring it up to Unity 2019, among other things.  Should be released soon.

**Comment by JustinFincher** [comment]
Thanks for clarifying, will wait for the update then :-)

**Comment by JustinFincher** [comment]
@iainbethune Hi, is there any update on this? I certainly understand the difficulty of pushing a new version in this WFH situation; it is just that Unity 2020 has already come out, which reminds me of this closed issue. Hope it gets updated soon! :-)

**Comment by ghost** [comment]
We're getting close, but no confirmed release date yet.
