### ISSUE TITLE
Prague

### ISSUE THREAD

**Issue by BrettGregson** [wrld3d/unity-api#109]
Unity 2019.2

No mapping data for Prague (50.0595849,14.325199)
Default location works, other European cities work (London, Barcelona) but Prague seems to have no mapping data despite Czech Republic having full coverage on the coverage map https://www.wrld3d.com/3d-maps/mapping-data#WRLD-MAP-COVERAGE

**Comment by ghost** [comment]
@BrettGregson coverage of the Czech Republic was added after the last release of the Unity SDK. To add it, you can follow the steps in this blog post: https://www.wrld3d.com/blog/wrld-expands-3d-map-coverage-with-46-countries-across-europe/

We'll be releasing a new SDK later this month which supports Unity 2019 and 2020, and has the latest map coverage included.

**Comment by ghost** [comment]
The beta docs page is here: https://docs.wrld3d.com/unity/2019.beta/latest/docs/examples/ and you can download the SDK from https://cdn1.eegeo.com/unity/2019.beta/wrld.unity.sdk.0.8.12.release.zip
