### ISSUE TITLE
Map does not load in build

### ISSUE THREAD

**Issue by d3vilsn0w** [wrld3d/unity-api#112]
Please take a look, seems to be an issue with Streamalpha. I already tried many ways to fix it. 

Using latest Unity, and latest SDK.

Tried that too, but doesn't work. 
https://github.com/wrld3d/unity-api/issues/76

Building it for a Mac. 

<img width="759" alt="Screenshot 2021-05-24 at 1 00 27 PM" src="https://user-images.githubusercontent.com/19762306/119312492-10e9c380-bc90-11eb-9cde-b6125c400ce4.png">

**Comment by ghost** [comment]
Hi, I can't recreate the issue myself... can you please confirm the version of the Unity Editor, WRLD SDK, the OS and hardware you are running on, and your Unity build settings?
