### ISSUE TITLE
World Coverage

### ISSUE THREAD

**Issue by blacqvve** [wrld3d/unity-api#114]
Hello everyone, I would like to learn is there a way to check a location is covered by WRLD3D map?

**Comment by ghost** [comment]
You can see our latest coverage and vote for new areas to be added here: https://www.wrld3d.com/3d-maps/mapping-data#WRLD-MAP-COVERAGE

We also build out areas of the map on request for individual customers for a fee (depending on the area you require) - please contact support@wrld3d.com if you're interested.

**Comment by blacqvve** [comment]
Sorry for missing information on my issue. I know WRLD3D has a map for displaying world coverage but i need to check is my player's current location covered by WRLD3D at runtime or before initializing the map.

**Comment by ghost** [comment]
Hi, it's not possible to check before initialising the map, but once the WRLD API is initialised you can:
* position the camera (or streaming camera if it's separate) at the location of interest
* check the children of the Terrain object
* If the enabled child objects name start with MissingLcm_ then we don’t have coverage for that area.

Hope that helps!
