### ISSUE TITLE
Error Message – mismatched node at connected road end

### ISSUE THREAD

**Issue by Ojayyy** [wrld3d/unity-api#116]
![image](https://user-images.githubusercontent.com/13174622/144105659-e59d08c6-e6aa-48b0-a186-d382751b6038.png)

When I load the scene "Rio de Janeiro", the following error message appears. When I load other locations (e.g. London, Paris, etc.), it works without problems. Unfortunately, I cannot interpret the message and want to ask you if you can?

Btw After the error message Unity crashes

### Additional Information

Unity SDK 0.8.103
Unity 2019.1.12f1

**Comment by ghost** [comment]
Hi @Ojayyy thanks for the error report.  We'll have a look and see if we can reproduce this ourselves.  The error message points to an issue with the road network data, which is likely to occur only at a specific location.  If you're able to give us the lat/lon of the region you're looking at when you see the issue that would be very helpful

**Comment by Ojayyy** [comment]
Here are the exact coordinates and location:

- Avenida Infante Dom Henrique Rio de Janeiro
- LAT: -22.916833
- LON: -43.173894

Btw I get the error message also with the Unity version 2020.3.22 - Just to make sure it's not the Unity version

**Comment by ghost** [comment]
Hi @Ojayyy we've fixed the root cause.  The relevant data has just been rebuilt and will be fetched automatically by the Unity app next time you run.  Let us know if you are still seeing the crash!

**Comment by Ojayyy** [comment]
Yes, error no longer occurs. If it's happen on another location, I will send you the coordinates ;-) Thx
