### ISSUE TITLE
Extend the sdk to load the osgb and 3dtiles models 

### ISSUE THREAD

**Issue by hcshen** [wrld3d/unity-api#118]
Hello, can wrld sdk be open source?  I am currently working on a metauniverse application and I want to modify the source code to implement loading osgb and 3dtiles models. How can I do this without modifying the source code?

**Comment by chrisdjali-wrld3d** [comment]
At this time, we've got no plans to open-source the whole Wrld SDK, and this is unlikely to change. The entire C# part of our Unity SDK is available for our customers to modify as part of their app, though, and that should give quite a bit of flexibility to change things.

Loading OSGB and 3D Tiles models shouldn't require any changes to the Wrld SDK, though. Once you've got a system to load the models into Unity, you can use our [`GeographicTransform` class](https://docs.wrld3d.com/unity/latest/docs/types/Wrld.Space.GeographicTransform/) to position their `GameObject`s in the world. Turning a 3D Tiles tileset into `GameObject`s should be relatively straightforward as it's a fairly simple JSON description of where things are in the world that references some glTF 2.0 models, and there are a few reliable glTF loaders for Unity. OSGB will be harder, though, as it was designed specifically to work with applications based on OpenSceneGraph, including data that isn't useful for anything else. Some OSGB files simply won't be representable faithfully with Unity's internal format, so won't look as intended. https://github.com/xarray/UnityOSGB appears to be an OSGB loader for Unity, but it's unclear whether it'll work for your needs.
