### ISSUE TITLE
Cached map

### ISSUE THREAD

**Issue by ArnoldBosch** [wrld3d/unity-api#12]
Hi there.

Very new to this and I added the map to a demo project to start playing around on it.

I noticed the map takes 1-2 seconds to load up, how would I go about downloading an area possibly by kmz or location+Radius?

I would like to actually download areas to a file or asset for offline use but getting it cached would also be fine.

Kind Regards
A.J

**Comment by Pirh** [comment]
Hi AJ,

We currently don't support downloading map data for offline use. However, the SDK does cache resources that have been downloaded while the map is running, so subsequent launches should be faster.

Allowing developers to pre-cache certain areas is something that we will consider for a future release of the SDK though. Thanks for the suggestion!

**Comment by ghost** [comment]
Precaching API was added in SDK v0.7: https://www.wrld3d.com/unity/latest/docs/examples/precaching-map-data/
