### ISSUE TITLE
HoloLens 

### ISSUE THREAD

**Issue by hg111** [wrld3d/unity-api#13]
Hello,  could the Unity SDK implementation work on HoloLens? What is required?

**Comment by malcolm-brown** [comment]
Hello, thanks for your interest in WRLD for Unity.

Unfortunately, integrating with the HoloLens technology requires supporting x86 architecture while our current Unity API only supports x86_64. As such it is not currently possible to integrate HoloLens with our Unity API. 

We've had some interest in supporting this, so we may provide x86 architecture versions in the future which would allow integration with HoloLens.

Hope this answers your question.
