### ISSUE TITLE
Zoom out from detailed map to "earth from space" view.

### ISSUE THREAD

**Issue by IvanPup** [wrld3d/unity-api#14]
Hello,

With Web Examples I can zoom out from lets say 3D map view with detailed buildings to 2D map view just with street names and then to "earth from space" view.
When I try to zoom out in Unity Example, the program stops working with the following notice: 
"Wrld ASSERT c:\buildagent\work\dc120b753cc54224\platform\EegeoUpdateParameters.h (49): Interest point altitude is too high."

Are there ways to make Unity Example works like WEB Example? 
I want the map to change the level of details when I zoom out instead of showing white screen filled with a distance fog.

**Comment by tim-jenks** [comment]
@IvanPup can you confirm which Unity Scene you are using?https://www.wrld3d.com/unity/latest/docs/examples/coordinate-systems/

What you describe is possible with the 'ECEF Space' and our stock camera controller (or your own camera controller if you feel more adventurous)

**Comment by Pirh** [comment]
We have managed to reproduce the issue and we have tracked it internally as a bug.

Thanks for reporting this and we will address this in a future release. If we discover any workarounds before then, we will add them here.

**Comment by jonty-dawson** [comment]
Fixed in v0.6
