### ISSUE TITLE
Map coverage

### ISSUE THREAD

**Issue by dashbg** [wrld3d/unity-api#15]
Hi there,

Can we help increase map coverage or are you able to cover the region of Bulgaria? We make an interactive tourist application with rich content and 3D tourist sites, by combining different AR and VR technologies. Your platform can help us a lot.

Best Regards
Dimitar Ivanov

**Comment by johnbell84** [comment]
Hi Dimitar,

I believe a colleague has already replied to a similar request via e-mail, but I've pasted the reply below as well for completeness.

Best Regards,
John

Hi Dimitar,

Thanks for your interest in our maps!

You can see our coverage here:

    https://www.wrld3d.com/3d-maps/mapping-data/

Unfortunately Bulgaria isn't included yet. Our goal is to have full coverage of Earth. We tend to prioritize new areas based on business leads, but we'll certainly take your question into account when we choose which areas to build next.

Best regards,
Judith
