### ISSUE TITLE
Build for HoloLens

### ISSUE THREAD

**Issue by Christoph142** [wrld3d/unity-api#19]
Currently it doesn't seem to be possible to use wrld for the HoloLens.
Unity states that WSAPlayer is an unsupported platform.

**Comment by tim-jenks** [comment]
Hololens is not something we support at the moment as we don't provide a UWP (specifically x86) build of WRLD only x86_64.

This is something we're considering adding so your feedback is welcomed. I've added this to the roadmap and if you keep an eye you should see this available soon.

**Comment by Christoph142** [comment]
Thanks for the update Tim. Looking forward to it.

**Comment by jonty-dawson** [comment]
Not for v0.7

**Comment by Dekamik** [comment]
Any progress on this? I'd love to see WRLD3D for HoloLens and Mixed Reality

**Comment by jonty-dawson** [comment]
Hi Dennis - this isn't currently scheduled for near-term milestones. See above for mention of the underlying x86 vs x86_64 issue that makes this non-trivial for us.
You've probably seen this already, but with v0.6 we have introduced experimental support for VR and AR targeting some other platforms - this may be of interest?

see:
https://wrld3d.com/unity/latest/docs/examples/whats-new-unity-sdk-0.6/
https://wrld3d.com/unity/latest/docs/examples/device-deployment-vr/
https://wrld3d.com/unity/latest/docs/examples/device-deployment-arkit/
https://wrld3d.com/unity/latest/docs/examples/device-deployment-arcore/

**Comment by Dekamik** [comment]
Hi Jonty, thank you for your rapid response.

I understand that the x86 issue creates some limitations, and I respect your decision. Is it possible for me to work around this by simply downloading a 3d model of a limited area?

The experimental support for VR is definitely of interest! Will look up on that later!

**Comment by jonty-dawson** [comment]
Hi Dennis - we don't support exporting parts of the WRLD 3d map as 3d models. The SDK is intended to be used to stream and display 3D maps, rather than providing models for use in other projects.

**Comment by Dekamik** [comment]
I understand, thank you for your support!
