### ISSUE TITLE
libStreamAlpha Dependency Does Not Support Compilation with Bitcode Enabled on iOS

### ISSUE THREAD

**Issue by FenderThinks** [wrld3d/unity-api#2]
At the moment the Unity API relies on a static library, "libStreamAlpha". This dependency is not compatible with iOS applications compiled with the "Enable Bitcode" flag set.

This causes compatibility issues with iOS 11 and ARKit, which require applications to be built with bitcode enabled. 

This is reproducible using the example package provided in the latest version of the Unity SDK.

**Comment by tim-jenks** [comment]
Thanks @FenderThinks, we have addressed this internally already to produce https://twitter.com/Faizaangeles/status/882798979536142338

We'll get a fix out to this as soon as we can.

**Comment by FenderThinks** [comment]
Hi @tim-jenks, 
Thank you for this info. We're looking forward to jumping in and testing it out. Any idea on timeline for pushing out the fix?

**Comment by tim-jenks** [comment]
Some point during Q3 I expect @FenderThinks . However, I don't believe you're blocked in experimenting with ARKit using WRLD Unity on iOS 11. A workaround in the mean time for this @FenderThinks is to just build your app without bitcode, we have been able to build + deploy WRLD ARKit on iOS11 without issue by disabling bitcode in the app.

@ArslanJafri has done this using WRLD Unity SDK to achieve the demo linked above on Twitter.

**Comment by jonty-dawson** [comment]
With 0.6 release, WRLD Unity SDK now supports ARKit, see https://docs.wrld3d.com/unity/latest/docs/examples/device-deployment-arkit/
