### ISSUE TITLE
Conflicts with Tango?

### ISSUE THREAD

**Issue by lawrencechau** [wrld3d/unity-api#20]
The demo scenes work fine when I build it to my Tango phone but after I add the Tango plugin to the project, things will start to break. I would build and run the same demo scenes after adding the Tango plugin to the project (not dragging any of the assets into the demo scene, but just simply importing the package over) and it would result in the message "Unfortunately, [app name] has stopped." and the app would close.

**Comment by tim-jenks** [comment]
Hi @lawrencechau - Could you please provide full log file from Unity and we'll investigate for you?

Additional information will also assist:
- Which device
- Which operating system incl. version

Cheers!

**Comment by lawrencechau** [comment]
I don't have a log file since it breaks within the Android application. If there's a method to get a log file while running the instance on your phone, I would love to know as it would really help me out with future testing.

As for everything else:
- Device: Lenovo Phab 2 Pro (Android 6.0.1)
- Operating System: Windows 10 Pro 64-bit
- Unity 5.6.1f1

**Comment by tim-jenks** [comment]
Android's logcat will get you device logs - if you can get those at point of crash it will help greatly.

**Comment by tim-jenks** [comment]
https://developer.android.com/studio/command-line/logcat.html

**Comment by lawrencechau** [comment]
[20170801_1128_WrldTangoTest.txt](https://github.com/wrld3d/unity-api/files/1191550/20170801_1128_WrldTangoTest.txt)

Here is a log from the start of the application to the end. It looks like the problem occurs around Line 1158

**Comment by tim-jenks** [comment]
@lawrencechau this looks like a race condition in our SDK. An onTouch event is occurring before our activities onCreate.

Could you elaborate on the specific reproduction steps?

**Comment by lawrencechau** [comment]
1. Create a blank Unity project and set the target platform for Android.
2. Go to the Unity Asset store and import the WRLD Unity SDK.
3. Open the UnityWorldSpace scene and paste the API key into your WrldMap component.
4. Enable "Use Built-in Camera".
5. Go to your Android settings, ensure the Package Name is set, the minimum API level is set to Android 6.0, and change device filter to ARMv7.

At this point, I would build to my testing device and confirm that the application works.

6. After the application has been confirmed to work, go to [Google Tango's Download](https://developers.google.com/tango/downloads) page and download the latest Tango SDK for Unity.
7. Open the SDK file and import everything to your current project.
8. With the same UnityWorldSpace scene, build the application to your testing device. Once the application has loaded, if you attempt any touch actions, the application will prompt you with a message saying the application has stopped and exit out.

**Comment by YohanBaillot** [comment]
This looks similar to issue #26 which I just reported. Same device, using OSX to compile with Unity 2017.2b11 but going from a Tango project working and adding Wrld, after which the project crash

**Comment by raintreesea** [comment]
I was able to resolve this problem in my environment (Windows 10, Unity 2017.2, ASUS ZenFone AR) by downgrading to Unity 5.6. I am just starting out, so I don't now yet if the Tango library works properly, but my basic app (a sphere hovering over a plane) no longer crashes after adding (but still not using) the TangoSDK asset.

**Comment by jonty-dawson** [comment]
Not explicitly addressed for 0.6, need retest
