### ISSUE TITLE
Adding items to the streamed asset collection

### ISSUE THREAD

**Issue by ZHumayunDeloitte** [wrld3d/unity-api#23]
I'm trying to add custom features with latlongalt positions based on a local dataset to a WRLD map based in ECEF space, and I'm having problems understanding how to properly do this.

I've experimented with adding an UpdateTransform call on the created object using my desired position converted from a LatLongAltitude to ECEF coordinate, but it doesn't seem to position the object as expected. Is there an example of how to add additional objects to the GameObjectRepository for them to be handled by WRLD as WRLD handles the streamed building/road/terrain assets?

Thanks.

**Comment by Pirh** [comment]
We've recently released a new version of our SDK on the Asset Store (version 0.5) that makes this much easier.

You can now use the [GeographicTransform](https://docs.wrld3d.com/unity/latest/docs/types/Wrld.Space.GeographicTransform/) component to position something on the map regardless of the world space you are using. You can either attach this component to the object you want to position, or you can attach it to that object's parent if you need a local position relative to that.

[This example](https://docs.wrld3d.com/unity/latest/docs/examples/position-object-at-latitude-and-longitude/) sounds like it should do what you need.

Thanks.
