### ISSUE TITLE
load self made models onto a basic map

### ISSUE THREAD

**Issue by saedrna** [wrld3d/unity-api#24]
Now it seems wrld is not possible to load user provided models onto the map. For example, I have an georeferenced kmz model, that could be loaded into Google Earth. For wrld, it would be awesome if I can just load my models and overlaid onto some basic map (e.g. OSM, google map, bing map or Baidu map in China)!

Best,

Han

**Comment by johnbell84** [comment]
Hi Han,

Thanks for your interest in our maps!  

You're correct that we don't currently support import of KMZ models.  As an alternative, you should be able to import any Unity-compatible model and position it in the world according to its latitude and longitude.  This involves adding a [GeographicTransform](https://docs.wrld3d.com/unity-SNAPSHOT/latest/docs/types/Wrld.Space.GeographicTransform/) behaviour to the GameObject, as shown in the following example:

    https://docs.wrld3d.com/unity-SNAPSHOT/latest/docs/examples/position-object-at-latitude-and-longitude/

We try to direct our development in response to user feedback.  I've recorded the request for KMZ support, so it may be something we're able to look at in future.

Kind regards,

John
