### ISSUE TITLE
Google Tango not working when Wrld AAR library enabled 

### ISSUE THREAD

**Issue by YohanBaillot** [wrld3d/unity-api#26]
Hello

I am unable to use Google Tango device when Wrld is included in my project. The Tango library seems to report not been able to access some Pose function when your AAR file in the library is present. I provided a sample unity project with the AAR file renamed AAR_ so that it is not taken into account. If you run the example in Assets/TangoSDK/Examples/Scenes/AugmentedReality on a Tango device you can see that you are able to drop some marker by clicking on the screen. When the AAR file is renamed correctly, the Tango scene then fails and ADB report pose on some Tango native functions. Can you please investigate on your side and see if there is a resolution?

The Asset folder of the Unity project is at https://www.dropbox.com/s/9vbrw2lw2c10nxj/Assets.zip?dl=0

and the AAR file fro Wrld is in Assets/Wrld/Plugins/Android/libs/armeabi-v7a

**Comment by tim-jenks** [comment]
Will investigate for you @YohanBaillot - sorry for the delay in getting back.

I can't commit to an exact date, will raise as priority 2 here so expect someone will look at it this week of 16th October.

**Comment by yanchuang0** [comment]
Why did I type the API key, and it still keeps me in this key:Please enter a valid WRLD Api key

**Comment by jlunderwood** [comment]
@yanchuang0 Please see https://github.com/wrld3d/unity-api/issues/39 and comment there if you are still having trouble.

**Comment by jonty-dawson** [comment]
Closing assumed no longer occurring
