### ISSUE TITLE
Support For Mixed Reality

### ISSUE THREAD

**Issue by sw-ms-ankitsangani** [wrld3d/unity-api#28]
Can you please support for UWP x86 project. so we can easily create builds for mixed reality (Hololens)

Thanks,
Ankit

**Comment by Pirh** [comment]
Hi there,

This is on our roadmap and tracked in this issue here #19. We'll post an update there when a UWP build becomes available.

**Comment by sw-ms-ankitsangani** [comment]
okay thanks @Pirh

**Comment by ambid17** [comment]
@Pirh any update on the build progress? I would love to use WRLD for Hololens in my project

**Comment by tim-jenks** [comment]
@ambid17 - please follow #19 for UWP support, this issue is a duplicate and is closed
