### ISSUE TITLE
Minimal Network Bandwidth to Use Unity API

### ISSUE THREAD

**Issue by silentsword123** [wrld3d/unity-api#29]
Hello,

Is there a minimal network bandwidth to load WRLD map in Unity Project? Our project basically streams map on street level of some large cities.  Thank you!

**Comment by jonty-dawson** [comment]
Hi 
The amount of data streamed by the SDK varies, depending on the area of the map being viewed. Dense urban areas with lots of buildings and roads have higher data size then low-population rural areas.
A typical street-level city view might use approximately 500KB data, and obviously more data is required as the viewpoint moves around the map and new areas come into view. There isn't really a minimum network bandwidth requirement, but in practice, on extremely slow networks (< 3G), some data requests may time out. This shouldn't be an issue on typical modern mobile or wifi connections though.
