### ISSUE TITLE
Changing Location of Camera without Enabling Default Camera Controls

### ISSUE THREAD

**Issue by Quidam2k** [wrld3d/unity-api#30]
It appears that the only way to change the geography displayed by the streaming camera is to make a call to MoveTo, which requires that "A non-null camera must be supplied, or have been set via SetControlledCamera."

There doesn't seem to be an override for MoveTo that allows a non-null camera to be supplied, which would mean the only way to do it is via SetControlledCamera. The problem with this is that it then allows the camera to be controlled by the default interface, and I don't want it to be.

Is there a way to set the latitude and longitude being streamed (I've already split streaming and rendering) without allowing the user to drag the map around or adjust the view using the mouse or touch input? I've tried clearing the controlled camera after it's been moved, but it seems that I need to wait for it to finish processing before doing so. Do I need to maybe write in some support for MoveStart and MoveEnd in OnCameraEvent?

Thanks!

**Comment by Pirh** [comment]
Hi there,

This depends on which [coordinate system](https://docs.wrld3d.com/unity/latest/docs/types/Wrld.CoordinateSystem/) you are using.

If you are using `UnityWorld`, you should be able to change the position of the Camera object directly. If you need to position it relative to a LatLongAltitude, you can use the conversion [here](https://docs.wrld3d.com/unity/latest/docs/types/Wrld.MapCamera.CameraApi/#vector3-geographictoworldpoint-latlongaltitude-camera) to convert it to World space.

Unfortunately, if you are using `ECEF`, the method for doing this appears to have a bug. (The answer would be to use the [SetOriginPoint](void-setoriginpoint-latlongaltitude) method, but at the moment, this calls MoveTo internally so does not work without a controlled camera.) We will fix this bug in a future release.

Of course, in either coordinate system you can specify your starting location by changing the 'Starting Latitude' and 'Starting Longitude' properties in the `Wrld Map` component's inspector. However, this cannot be changed at runtime.

If you're using UnityWorld space, I hope this solves your issue. If not, I'm sorry. We will keep investigating this issue and update you when we fix the bug, or if we find any workarounds.

**Comment by jbrownwrld** [comment]
Hello, 
This issue has been fixed as of v0.6; you may now supply a boolean delegate to the `CameraApi` to manage when to apply the built-in camera controls to the controlled camera. This is done with the `CameraApi.RegisterShouldConsumeInputDelegate` in [CameraApi](https://wrld3d.com/unity/latest/docs/types/Wrld.MapCamera.CameraApi/).
To disable them entirely, you can use a simple function that always returns false.
