### ISSUE TITLE
GeographicTransform not setting height

### ISSUE THREAD

**Issue by YohanBaillot** [wrld3d/unity-api#31]
Hello, the GeographicTransform and API is great to set some specific POI on the map, however the capability is pretty much useless without knowing the height of the terrain at that latlong so that the object can actually be set above the ground when the ground is not at sea level. Can you please provide a function returning the terrain height at the lat/lon coordinate or make sure that the capability set that height accordingly?

**Comment by tim-jenks** [comment]
Thanks @YohanBaillot - we will add this extension to support an elevation mode that is above ground not above sea level.

**Comment by YohanBaillot** [comment]
Hi, wondering if you now have a capability to do so?

**Comment by jonty-dawson** [comment]
Available with v0.6 release, please see Positioners: https://docs.wrld3d.com/unity/latest/docs/types/Wrld.Space.Positioners.Positioner/
Also relevant: 
https://docs.wrld3d.com/unity/latest/docs/examples/fly-object-over-map/
