### ISSUE TITLE
Map doesn't load sometimes

### ISSUE THREAD

**Issue by omarbatao** [wrld3d/unity-api#32]
Hi!
i'm new with wrld unity sdk and its a cool stuff!

I've got a problem: sometimes map is not loading on my scene and i haven't got any error in console...

maybe a wrong configuration? or something else?

<img width="346" alt="schermata 2017-10-06 alle 17 15 48" src="https://user-images.githubusercontent.com/13422180/31284912-3f97a760-aaba-11e7-94ce-584aaa57a79b.png">

**Comment by GabrielBakker** [comment]
One big cause for this when I was debugging in Unity, is that I have
multiple monitors. The map stops loading if its not the active task. For
me, especially, I was using VR with the SteamVR Plugin. When you're running
a VR application, the VR controls continue to work just fine even if the
app looses focus. So from within the headset I couldn't tell that it was
loosing focus.

The WRLD map stops streaming if the app looses focus. If you experience
this problem, click on your app in its active window to make sure it gets
focus again, and see if the map starts streaming again.

Gabriel

**Comment by malcolm-brown** [comment]
Hi omarbatao, 

Configuration looks mostly fine, however if you're not using the built-in controls you'll be responsible for positioning the camera yourself in a local space.  If you try enabling the built-in camera controls and then run the scene, you should hopefully see Liberty Island with no problems!

If you wish to manually control the camera, it's worth [reading up on the example here](https://wrld3d.com/unity/latest/docs/examples/using-your-own-camera-controls/). You'll need to manually position and rotate the camera to look where you expect, and you'll need to manually call StreamResourcesForCamera() once per update.  

Hopefully this should get the map showing for you.

We're also aware of an issue where the map won't stream in when the application loses focus, and will investigate and hopefully resolve this soon.

**Comment by dellams** [comment]
Hi there,

The map appears for me if I play it within Unity but if I build for MacOS or Android I just get a light grey screen, any ideas?

I have the API Key set OK or it wouldn't stream in as it does within the Unity editor.

Is there something else I am missing?

Many thanks,
David.

p.s. Love your work, been following you from the early eeGeo days... been waiting for a usable Unity version before starting to work with, have big plans for this once I can get it working, thanks! :)

**Comment by ghost** [comment]
Unable to recreate - please re-open if this is still an issue for you.
