### ISSUE TITLE
Api.Instance null in editor and failing on initial processing needed 

### ISSUE THREAD

**Issue by YohanBaillot** [wrld3d/unity-api#34]
Hello,

On the editor (at least, not confirmed on other platforms), the Api.Instance is sometimes not defined at runtime at start and some processing needed to be executed fails as a consequence. For example

void OnEnable()
	{
Api.Instance.GeographicApi.RegisterGeographicTransform(avatarTransform);
	}

is failing in the editor reporting Api.Instance as null, till I put a check, however in this case the process does not fails but the transform is not initialized

It seems that you should have a process to make sure that everything is defined before setting things up. Any suggestions?

**Comment by tim-jenks** [comment]
Apologies for the delay in getting back @YohanBaillot 

This will be investigated as a priority defect.

**Comment by jonty-dawson** [comment]
Not seen occurring in v0.6, believe fixed
