### ISSUE TITLE
Building height based on LatLong

### ISSUE THREAD

**Issue by silentsword123** [wrld3d/unity-api#35]
Hello,

We tried to use raycast and colliders to get the height of a building at a given location, however, it reduced the performance dramatically. Is there a simple way for us to get the terrain height and building height at a given LatLong coordinate? 

Thanks!

**Comment by jlunderwood** [comment]
Yes, you can use the [BuildingsApi](https://wrld3d.com/unity/latest/docs/types/Wrld.Resources.Buildings.BuildingsApi/), in particular GetBuildingAtLocation.  The [Building](https://wrld3d.com/unity/latest/docs/types/Wrld.Resources.Buildings.Building/) object passed to the callback contains both the base altitude and top altitude.
