### ISSUE TITLE
ARKit PickBuilding

### ISSUE THREAD

**Issue by MephestoKhaan** [wrld3d/unity-api#36]
I am trying the simple task of picking buildings using the sample but using arkit. And it always select the same one (the centre one), even thought the LatLong that I am getting with the code is different.

Edit:
Just to add more info, I just tried with something as simple as this:

```
void HighlightAtPosition (Vector3 tapPos)
		{
			var ray = lookingCamera.ScreenPointToRay (tapPos);

			RaycastHit hit;

			if (Physics.Raycast (ray, out hit))
			{
				var viewportPoint = lookingCamera.WorldToViewportPoint (hit.point);
				var latLongAlt = Api.Instance.CameraApi.ViewportToGeographicPoint (viewportPoint, lookingCamera);

				Api.Instance.BuildingsApi.GetBuildingAtLocation (latLongAlt, OnBuildingSelected);
				Api.Instance.BuildingsApi.HighlightBuildingAtLocation (latLongAlt, highlightMaterial, OnHighlightReceived);
			}
		}


		void OnBuildingSelected(bool success, Building b)
		{
			Debug.Log (b.BuildingId);
		}

```

I can confirm the latLongAlt has been different every time. But the `b.BuildingId` being printed has been the same always

**Comment by tim-jenks** [comment]
Could you please provide some example lat,lons that you are experiencing issues with?

Additionally, the buildingId returned would also help.

I'd recommend trying to debug visualise the Ray here: `var ray = lookingCamera.ScreenPointToRay (tapPos);` as this will help you to diagnose the issue.

**Comment by MephestoKhaan** [comment]
I did a small project that shows the problem, here is the link:

Selecting building at: 37.8024105318418  -122.405865930829
Selected landmark_us_sf_coittower01

Selected landmark_us_sf_coittower01

Selected landmark_us_sf_coittower01

Selected landmark_us_sf_coittower01

Selected landmark_us_sf_coittower01

Selected landmark_us_sf_coittower01

**Comment by boblaublaw** [comment]
Quick nudge to check status here.  (Luca and I are working together on this project.)

**Comment by tim-jenks** [comment]
Thanks, we'll investigate this for you as a priority!

**Comment by malcolm-brown** [comment]
Believe what you want to use in this case is the `[WorldToGeographicPoint](https://wrld3d.com/unity/latest/docs/types/Wrld.MapCamera.CameraApi/)` method - this lets you convert a local Unity position into a LatLongAltitude for use with the Buildings API.  

```
void HighlightAtPosition (Vector3 tapPos)
{
	var ray = lookingCamera.ScreenPointToRay (tapPos);

	RaycastHit hit;

	if (Physics.Raycast (ray, out hit))
	{
                var latLongAlt = Api.Instance.CameraApi.WorldToGeographicPoint(hit.point, lookingCamera);

		Debug.Log(string.Format("Selecting building at: {0}  {1}",latLongAlt.GetLatitude(), latLongAlt.GetLongitude())); 
		Api.Instance.BuildingsApi.HighlightBuildingAtLocation (latLongAlt, highlightMaterial, OnHighlightReceived);
	}
}
```


However, there's a bug where the `WorldToGeographicPoint` doesn't work if the root `WrldMap` object is being scaled, and in your project, it's being scaled by 1/1000.  We'll get this fixed for the next release, but in the meantime you can work around this by making the following changes to `Wrld/Scripts/ApiImplementation.cs`:

1. Add field `private Transform m_parentTransform;`
2. Assign it in constructor via `m_parentTransform = parentTransformForStreamedObjects;`
3. In the `WorldToGeographicPoint` method (line 234) modify the code to be the following:
```
internal LatLongAltitude WorldToGeographicPoint(Vector3 position, Camera camera)
{
    if (m_coordinateSystem == CoordinateSystem.UnityWorld)
    {
        position = m_parentTransform.worldToLocalMatrix.MultiplyPoint(position);
        return m_frame.LocalSpaceToLatLongAltitude(position);
    }
    else
    {
        var ecefPosition = m_originECEF + position;
        return LatLongAltitude.FromECEF(ecefPosition);
    }
}
```

This should transform the point into its correct space for conversion to a LatLong, and you should start seeing the correct buildings highlighting.

**Comment by MephestoKhaan** [comment]
Thanks I will try this asap. I suspected it was something related to the scale of the map indeed.

**Comment by MephestoKhaan** [comment]
Just as a note, I suspect the opposite (positioning elements in world space using latlong) will also be a problem if the map is scaled down. Is that something going in in the next update as well? Do you have an ETA?

**Comment by malcolm-brown** [comment]
You're right in that the other transforms will need similar modifications to get working too.  

We're going to schedule to get the SDK properly handling scaling + transforms for a future release,

**Comment by MephestoKhaan** [comment]
Hi! I will need a similar fix for Geographic transforms, right now they appear all far away from where they should and I imagine it is the same problem. Tried modifying GeoToWorld but did not affected it.

**Comment by malcolm-brown** [comment]
Making the object with the GeographicTransform component a child of the WrldApp object that is being scaled should hopefully address this - its position should then be scaled along with the rest of the world.   

We'll make a note to ensure GeographicTransforms also work correctly with a scaled map as well, reguardless of where they are in the scene, for the next release.

**Comment by yosun** [comment]
Just checking if this has been fixed?

**Comment by jonty-dawson** [comment]
Likely need to add API point to nominate a Unity camera as the instance for which projection-related API points will pull camera state from.

**Comment by tommymacdonald** [comment]
Tracked internally as MPLY-9058.

**Comment by ghost** [comment]
Believe this is now fixed - please re-open if not.
