### ISSUE TITLE
Get Altitude from Latitude and Longitude

### ISSUE THREAD

**Issue by Quidam2k** [wrld3d/unity-api#38]
I was looking around for it, but couldn't find a way to get the altitude for a given geographical point. There are ways to get it from screen point or viewport point or world point, but I feel there's got to be a way to get it just from the latitude and longitude. Am I missing something obvious?

**Comment by jonty-dawson** [comment]
Hi - on our Unity api, there isn't currently a straightforward way of obtaining the altitude of the terrain or other map feature at a given lat-long. We plan to add a way of obtaining this soon, no definite date yet though.
The reason it isn't possible to obtain an altitude direct from a latitude and longitude is that it is dependent on streaming in the map features for that geographic location, then sampling the feature geometry to obtain an altitude.

**Comment by Quidam2k** [comment]
But aren't you pulling the altitude for a given location when you build the map? I would imagine the same database that's used to form the terrain could be accessed in order to provide the altitude for a specified lat & long.

**Comment by jonty-dawson** [comment]
Yes, we make use of terrain elevation data when building our maps. The way that our maps work is that we don't have a web service as such for providing elevation information. Instead, we stream our map tiles, which include full 3d terrain models, then query these streamed resources on the client. 
Currently on our Unity Api there isn't a convenient way of doing this - but we have work underway to provide this, likely for next release.

**Comment by yanchuang0** [comment]
Is not the map of the Chinese map now?

**Comment by yanchuang0** [comment]
Is there no map information in China yet?

**Comment by jonty-dawson** [comment]
Our map coverage does not include China yet.
See https://www.wrld3d.com/3d-maps/mapping-data for further information about areas currently mapped.

**Comment by jonty-dawson** [comment]
With v0.6, can use https://docs.wrld3d.com/unity/latest/docs/types/Wrld.Space.Positioners.Positioner/ to query the terrain elevation for a latitude-longitude coordinate, receiving notification as and when terrain is streamed in. See also:
https://docs.wrld3d.com/unity/latest/docs/examples/fly-object-over-map/
