### ISSUE TITLE
Troubleshooting error message: "Please enter a valid WRLD Api key"

### ISSUE THREAD

**Issue by jlunderwood** [wrld3d/unity-api#39]
If you are getting the "Please enter a valid WRLD Api key" message, please check the following:

1. You have registered at https://accounts.wrld3d.com/users/sign_up
1. You have created an API key from this page:
https://mapdesigner.wrld3d.com/portal/latest/dev/
![apikey](https://user-images.githubusercontent.com/19375948/31762095-0d3914be-b4b2-11e7-94f6-5d1f3f2cc88b.jpg)
Your API key is not the same as your developer token. You can have many API keys associated to your developer token; in general, you will want a different API key for each application you create using our maps.
Note that the developer token is 80 characters long; an API key is 32 characters.
1. Your API key has been added to the WrldMap GameObject, following the instructions at https://wrld3d.com/unity/latest/docs/api/ .  You may need to save the project to ensure this change is applied.

**Comment by yanchuang0** [comment]
Blame my eyes too small，,did not see
