### ISSUE TITLE
GetThreadContext failed

### ISSUE THREAD

**Issue by yanchuang0** [wrld3d/unity-api#40]
When I run wrld3d in unity, why a run will appear: Fatal error in gc, GetThreadContext failed, who can help me

**Comment by johnbell84** [comment]
Hi Yanchuang0,

Thanks for trying our maps and getting in touch, I'm sorry to hear you've encountered a problem. I don't think I've heard of this sort of issue with our plugin before. We'd like to collect some further information to see if we can reproduce the problem, please.  Specifically, the following details:

    Which Unity version were you using?
    Which platform were you running on?  As much detail as possible about OS versions etc. would be ideal here.
    Could you tell us which example you were running, or if it was your own scene?
    If this tends to happen when you're viewing a particular part of the world, it would be great if you could give us a latitude and longitude.
    Did the problem happen straight away, or after some time?  Any information you'd be able to give on how repeatable the crash was would be great.

Finally, if you've any additional tips about how to reproduce the issue, that would be great.  A few search results suggest that similar errors with Unity programs on Windows are sometimes associated with antivirus programs (Avast, Kapersky) or anti-cheating software such as FaceIT.  Any information you'd be able to give about whether you're running programs of that sort might also help us to track this down.

Thanks again for your help.

Kind regards,

John

**Comment by ghost** [comment]
No info on how to reproduce
