### ISSUE TITLE
Q: Deploying on Linux

### ISSUE THREAD

**Issue by mvollrath** [wrld3d/unity-api#43]
In the "[Getting Started](https://wrld3d.com/unity/latest/docs/api/)" docs there are instructions for deploying to Windows, OSX, iOS, and Android.

Can WRLD be deployed on Linux?  Is this supported?

**Comment by malcolm-brown** [comment]
I'm afraid we don't support Linux at present. We'd love to support it one day but it isn't on our road map for the near future.  This of course could change depending on demand.

**Comment by ghost** [comment]
No plans to support Linux at present
