### ISSUE TITLE
Wierd Building Blocks

### ISSUE THREAD

**Issue by amitchai** [wrld3d/unity-api#44]
Hi,
I actually found out this after a long time that I've gotten used to the issue. After starting a new project I've realized something is not working right in my project. can't figure out what it is. the picture will represent the "Block" of building with camera wide angle. the map reveals only terrain and a square area of buildings. while in the other pic, it seems natural. What can be done to resolve this? 

https://drive.google.com/file/d/0BwImFr8UHq3kdjM0cUIwVm5Rbnc/view?usp=sharing
https://drive.google.com/file/d/0BwImFr8UHq3kSWdWb1NlSTlXelU/view?usp=sharing

**Comment by malcolm-brown** [comment]
This is sounding similar to https://github.com/wrld3d/unity-api/issues/7

These 'blocks' you're seeing are how we split the map up for efficient streaming and rendering. Which blocks are loaded in is dependent on what camera you're using to stream - by default this whatever your camera you have attached to the WrldMap component, but you can provide your own via `Api.Instance.StreamResourcesForCamera()` (more info at https://wrld3d.com/unity/latest/docs/examples/using-your-own-camera-controls/)

![image](https://user-images.githubusercontent.com/1670005/32323201-1d4962f6-bfbf-11e7-8eca-f1d35e953f1d.png)

As you can see, what data is being streamed in is determined by the camera's Frustum - you can change the camera's near/far and Field of View values to stream in more.

![image](https://user-images.githubusercontent.com/1670005/32323264-6073a078-bfbf-11e7-91fa-1278cbe3b57b.png)

There are a few things to note:

- It's worth checking the "LOD Based On Distance" option on the WrldMap component.  This will use larger, lower detail versions for blocks in the distance, which will improve performance at hopefully no noticable cost.
- The larger size of the camera Frustum (near/far values and the FoV value), the more data will be streamed in - be wary of streaming in more than you need for performance reasons
- A view all the way to the horizon may be quite costly, so you might want to consider introducing some fog to the scene to mask the edge - we do this in the UnityWorldSpace scene, and you can see how you'd mask the 'edge' of the visible world like so:

![image](https://user-images.githubusercontent.com/1670005/32323479-0e32b5dc-bfc0-11e7-9281-89317ece3676.png)

Please let us know if this resolves your issue.
