### ISSUE TITLE
Unity freezes when debugging EcefSpace.unity scene

### ISSUE THREAD

**Issue by JoeySc** [wrld3d/unity-api#47]
Unity is freezing when I debug the EcefSpace.unity scene.
First I open the EcefSpace.unity scene and attach Visual Studio for debugging, then I step through execution starting from WorldMap.Awake().  I can step to the constructor of NativePluginRunner and then execution freezes when I get to the Initialize() function (NativePluginRunner.cs, line 98).

Any ideas?

**Comment by johnbell84** [comment]
Hi JoeySc,

Thanks for trying our maps.  I'm afraid you've run across a problem that we also encounter internally.  At the moment, Microsoft's Visual Studio Tools for Unity do not support debugging of code that calls into native DLLs:

	https://docs.microsoft.com/en-us/visualstudio/cross-platform/using-visual-studio-tools-for-unity#debugging-a-dll-in-your-unity-project

It looks like in your case the debugger is failing during the first call into native code.  Sadly this isn't something we have a workaround for at present.  We'll update this issue if we can find a solution.

Kind regards,

John

**Comment by JoeySc** [comment]
Thanks for your response John,

This is a pretty significant obstacle since it also prevents us from debugging our code so long as Wrld is part of our project.  Is there really no way to get around this issue (even some non-ideal solution)?  Its hard to imagine that your team managed to build a stable SDK release without any Unity debugging capability.

Joey

**Comment by jonty-dawson** [comment]
Currently no known workaround for this (see above Microsoft link)
