### ISSUE TITLE
Can we load ECEF map with an additional camera?

### ISSUE THREAD

**Issue by silentsword123** [wrld3d/unity-api#48]
Hello! Is it possible to stream the ECEF map with an additional camera? If it is, how could we control the map loading area? Thanks!

**Comment by tim-jenks** [comment]
Hi @silentsword123 

It's possible to separate the visual camera, from the camera frustum used to stream resources

This is briefly explained at the bottom of the documentation here: https://wrld3d.com/unity/latest/docs/examples/using-built-in-camera-controls/

Hope this helps

**Comment by silentsword123** [comment]
Hi @tim-jenks 
Is there a more accurate way for us to control the map loading area when using ECEF system? For now I noticed that the camera's position, rotation, FOV and clipping plane could effect the loading area, but how could we get more precise control on it. Thanks!

**Comment by jonty-dawson** [comment]
Hi @silentsword123

The WRLD Unity SDK streams in map data for the potentially visible area - so any map "tiles" that are partially or completely inside the streaming camera's frustum. The camera position, orientation, FOV and near/far clip distances all affect this frustum.
