### ISSUE TITLE
Question: Recommended method to determine if coverage is available for a given location

### ISSUE THREAD

**Issue by AubreyF** [wrld3d/unity-api#49]
Greetings WRLD team! I'm working on a prototype vehicle combat/exploration simulator, and will be experimentally integrating your streaming terrain library over the next few weeks to assess it's potential applications in a fast-paced first-person experience.

In this simulation, I need to determine if coverage is available through your library for a given location. I am currently attempting to load the location, waiting a few seconds, and then raycasting through the origin of the scene.

Is there a more streamlined approach that you can recommend? Ideally, this would be something like an API call such as Wrld.Api.TryGetAltitudeAtLocation (LatLongAltitude, Double&).

**Comment by tim-jenks** [comment]
Agree, this is missing and have accepted onto roadmap for inclusion in a future release, ideally 0.6

**Comment by AubreyF** [comment]
Great, thanks! I'll close this issue for now.

**Comment by ghost** [comment]
No current plan to implement this.
