### ISSUE TITLE
Near-camera tiles need to be prioritized

### ISSUE THREAD

**Issue by AubreyF** [wrld3d/unity-api#51]
I'm calling StreamResourcesForCamera every frame, but experiencing tiles near to the camera not being rendered even though further tiles are rendering correctly. (Please see attached screenshot).

Camera far clip plane: 10,000 (This issue begins surfacing when far clip plane exceeds 5,000 or so).
Unity version: 2017.2.0f3
Whirld lib version: 0.5

![core_11-18-2017_1-08-15_pm_976](https://user-images.githubusercontent.com/2789037/32984769-a808877e-cc61-11e7-8e64-ae55d4cefbea.jpg)

**Comment by malcolm-brown** [comment]
This certainly isn't expected - the API should stream in all the cells that intersect with the streaming camera's frustum.  Can you give us some more information? 

- Are you using a separate streaming + rendering camera?
- What are the _near_ and _far_ clip plane values for your streaming camera?
- What's the lat/long of this area of the world?

This should help us track down the issue.

**Comment by AubreyF** [comment]
Hi @malcolm-brown, I was just able to track this down in a repro scene and it isn't what I had initially assumed. You are correct, and WRLD's frustum culling is working as expected.

The missing world chunks reported above were due to a "floating origin" system active in the scene in question, which was periodically translating the main camera and all scene geometry to keep the player nearer to Unity's scene origin to minimize physics and shadowmap precision issues. I will update this origin reset system to update WRLD's base lat and lon during translation events, which should solve things properly. In the mean time, closing this issue and apologies for calling 🐺
