### ISSUE TITLE
Drivable roadways

### ISSUE THREAD

**Issue by AubreyF** [wrld3d/unity-api#52]
Greetings WRLD team! I'm working on a prototype vehicle combat/exploration simulator, and will be experimentally integrating your streaming terrain library over the next few weeks to assess it's potential applications in a fast-paced first-person experience.

One of the extremely interesting aspects of WRLD (currently Unity library 0.5) are your collision-enabled roadways. Unfortunately, these roadways are only marginally drivable in their current form. Most specifically, road and railway surfaces inexplicably mirror terrain slopes in all the areas I have explored. Keeping roadways level would allow them to both look more realistic, and be navigated without vehicles rolling sideways off roadways running through mountainous regions. Here are a few of my requests. I'd love to get your feedback as well!

1) Keep roadways level, with their "uphill" side matching the level of the terrain they are placed on.

2) Introduce subtle "banking" to high-speed roadways, carving into turns as all real-life roadways are.

3) Create an optional "roadways" API that would provide spline data for road surfaces rather than fully generating low-rez meshes for them as is currently done. I have already written code to generate smooth banked roadways in real time, and am salivating at the possibility of creating a WRLD-powered racing simulator in Unity.

![core_11-18-2017_1-12-54_pm_259](https://user-images.githubusercontent.com/2789037/32984851-16baece2-cc63-11e7-8725-37a9c5a3ea4a.jpg)

**Comment by tim-jenks** [comment]
Hi @AubreyF - thanks for the insight and comment

I can't give you date, but I can tell you what we have in the works to deal with this:

1. 'Stitching' roads and terrain, this means that road that is 'on the ground' would be part of the ground mesh. This will avoid the issues with the current roads where they are actually slightly above ground height to deal with depth-buffer precision issues leading to z-fight. For elevated road segments, we will still elevate them above terrain.

2. Exposing of polyline-based navigation graph data underlying the roads in the Unity SDK. This information is currently available in our underlying C++ SDK but isn't exposed in the Unity API, and is used in our C++ for other effect like driving traffic-AI or routing overlay.

It's just a matter of priority for us. I'll leave this open and will update when there is movement on our side.

As a note the screengrab you depict is actually of railway, which we intentionally raise up for stylistic effect.

**Comment by malcolm-brown** [comment]
Hi Aubrey, these are good suggestions and we'll take them on board when deciding on future work.  It's likely implementing either 1) or 2) will probably be much further down the line, but we may expose some of 3) in the near future as we already have some of this information internally.  We'll keep this issue updated as with any developments!

**Comment by AubreyF** [comment]
Thanks @tim-jenks! Exposing the underlying nav data is exactly what I am looking for. I'm quite excited to experiment with this, once available. Stitched roads also sound like they will provide an opportunity to generate smoothly banked roadways directly above the terrain surface for select roadways in racing simulators.

Yes - I provided a screenshot of the railway intentionally, as it's raised nature helps to visually emphasize that it is sloped to match the underlying terrain even though it wouldn't be in the physical world.

**Comment by ghost** [comment]
TransportApi and related were added in SDK v0.8 https://www.wrld3d.com/unity/latest/docs/examples/access-network-using-transportgraph/
