### ISSUE TITLE
Rendering Feedback

### ISSUE THREAD

**Issue by GabrielBakker** [wrld3d/unity-api#53]
Hello,

I made a little Hot Air Balloon game using WRLD. Its made for the HTC Vive but it works fine in non-VR as well. You're all welcome to try it out if you like, at http://www.sageax.com/games/balloonride/.

We spoke previously, and you encouraged me to try the latest version of WRLD in my game and enable the "LOD based on Distance" option, to see if that would resolve the issues I was having.

Thank you for your advice and encouragement.

The new "LOD based on Distance" option certainly helps. Understandably there's going to be lag any time you're loading a large viewing area of thousands of objects over the internet, and "LOD Based on Distance" really helps to focus resources on the visual elements that are most important.

Also, when you're in a hot air balloon, the balloon tends to go up and down a lot due to wind and air density and temperature fluctuations, and that action was causing the old "LOD based on Elevation" system to go crazy, constantly loading and reloading the terrain at different LODs.

However, while it helped, several Rendering issues remain, particularly for Games that make use of VR.

The WRLD map unloads objects that fall outside the view range and culling area. Then it reloads them when they flow back into the view. But Users of VR Games tend to turn their head a lot. Just imagine shaking your head "No" while wearing VR in a large scale WRLD scene -- the objects are constantly unloading and reloading, which not looks goofy and takes the user out of the experience (by reminding them that they're in a game), but it also unnecessarily wastes a lot of resources.

I wonder if there's any way you could leave objects for a few seconds and only unload them if they stay out of the view for a while. Also, wait to unload them until they're WAY out of the view. This would reduce the number of objects that WRLD tries to unload and reload all the time (at a slight, but worth it, cost in memory usage), making the experience a lot smoother, especially for VR applications.

Gabriel

**Comment by AubreyF** [comment]
You may want to check out my discussion from last week in #50 (Idea: Accelerated visual and physics mesh generation). The "floating target camera" approach Tim and I discussed has limitations, but it is a step in the right direction.

**Comment by GabrielBakker** [comment]
Yes, I'd noticed you wrote about the same features, in fact that helped
encourage me to make another attempt at my project.

I also had that conversation with them in July when I first started working
on this. They directed me to the floating target camera approach (which i'm
already using) and then later they suggested that I try the latest version
for its LOD based on Distance feature (which I have now tried as well).

Both of those helped, but neither one solved the problem. So when I saw you
posting about the same issues I realized i must not be the only one who
needs these features! And I wanted to lend my support to the conversation
you were having, provide another voice in favor of your feature request.
Its a needed feature and the game i'm working on can't progress much
farther.


Also I wanted to suggest a couple approaches, like using timing or
measuring the steadiness of the head direction to determine how to behave,
or just making it an option. I can see the reason they want to do it the
way they do, for situations where the camera moves slowly their approach is
perfect. But in my situation (and i'd guess yours as well) the camera
changes directions more quickly and it becomes pretty noticeable.

Gabriel

**Comment by AubreyF** [comment]
@GabrielBakker I love your project, can't wait to see where it goes from here.

Are you pointing your floating camera straight down? This should nicely solve the issue of unloading objects the user is near to, but facing away from.

**Comment by GabrielBakker** [comment]
When I pointed my floating camera straight down i ended up not getting
enough coverage of objects in the distance, such as the mountains that form
an iconic backdrop to some cities.

I really like being able to have the long view distance that allows the
background scenery to fade into the fog color in the distance. if i point
the camera down and make the FOV really super wide, wide enough that you
can still see the mountains, then i end up with the problem of having
everything loading and then it is choppy of course. I don't really need
them to keep everything loaded all the time, and i understand why they
don't do that. I don't think they should try to load areas that are outside
of the players view angle.

All I'm saying is that once loaded, they shouldn't UNLOAD an object just
because it passed outside the players view angle. AT least wait a few
seconds to make sure they're not just shaking their head.

Gabriel

**Comment by AubreyF** [comment]
Great discussion. I'm still experimenting with different FOV's and atmospheric styles that make them feel more or less believable. I agree that the visibility of iconic backdrops is critical. Here's an idea... Granted, this is something that WRLD is in a better position than you or I to do, but we could implement our own culling systems by manually enabling and disabling the mesh entities that WRLD streams in. I'll be doing some integration work later today, and may have a chance to test this approach. Will let you know if anything comes of it!

**Comment by GabrielBakker** [comment]
Thats a great idea and I'd be willing to try.

But my goal is to NOT cull the mesh entities the second they slip out of
the view, my goal is the opposite: to prevent culling them. Maybe i'm
missing something obvious here, but I can see how I would manually cull
something but I don't know how to manually prevent WRLD from culling
something.

Gabriel

**Comment by AubreyF** [comment]
My thought was that we could prevent WRLD from culling (while still benefiting from the LOD system) by defining a render target camera floating above the player and looking straight down. We could then toggle the activation status of MeshRenderers attached to each mesh building/tile according to any desired culling logic - including a configurable delay after leaving the player's camera's frustum. Here's a system I have played with in the past that employs a ray-intersection-timer-based occlusion approach: https://forum.unity.com/threads/instantoc-dynamic-occlusion-culling-lod.166748/

I'l report back with notes once I have had a chance to test this approach.

**Comment by GabrielBakker** [comment]
I tried it. Here's what happens:

When you point your render target camera straight down, you're causing it
to stream stuff equally in all directions. First of all, that makes it so
that objects in the distance never render. The user always sees jagged
edges to your world and blackness beyond, because WRLD thinks that stuff is
outside of the down-ward pointed camera fustrum.

The second problem is you're now wasting bandwidth by streaming in
resources from behind the player when the player might never even look in
that direction. So, rather then prevent WRLD from Culling, you're actually
forcing WRLD to stream in and load additional stuff, further reducing
performance. So you get a choppier experience to go with your jagged edges
of the world.


So thats totally different then what we're trying to accomplish here. What
we want is stuff to:
1) Never Stream until the Player Looks at it.
2) Stream all the way to the far clipping plane of the viewing camera (not
just localized to the terrain right below the balloon).
3) Remain on the screen for an extra 3 seconds when the player is no longer
looking at it.

Number 3 is the only thing we need that isn't there now, using the standard
camera. I'm afraid I don't understand how this approach you're describing
could help us achieve number 3. But it certainly seems like it will stop us
from achieving number 1 and 2.

Gabriel

**Comment by jlunderwood** [comment]
Just wanted to say that we're following this discussion here at WRLD.  I don't think we have anything just now to support the behaviour you're looking for.  Streamed data is cached, which should help, but our efforts to keep the memory footprint to a minimum are probably causing the issue in this context.  We'll keep this request in mind as we work on future releases.
