### ISSUE TITLE
Location Data

### ISSUE THREAD

**Issue by GabrielBakker** [wrld3d/unity-api#54]
I'm working on a WRLD exploration (hot air balloon) game.

Right now I have a hard coded list of locations in my game, and the user selects from that list. Its basically a list of "Featured Cities", and the associated Lat Long coords for those cities. They're each cities that I noticed you had good coverage of. I wanted to direct users to the parts of the map that are already done.

But you're adding more coverage to your map all the time, and each time I need to search around the map and find good places to add to the "Featured City" list.

Do you publish a list of the latest additions to your map anywhere? Or (ideally) is there a way to query the API for a list of places that have good coverage?

Gabriel

**Comment by AubreyF** [comment]
Hi @GabrielBakker! I posed a similar question a few days ago. https://github.com/wrld3d/unity-api/issues/49

Official response: "Agree, this is missing and have accepted onto roadmap for inclusion in a future release, ideally 0.6"

**Comment by GabrielBakker** [comment]
Well, sort of. You want to check if coverage exists at a given location.
Whereas i'm looking for a list of locations with good coverage.

I could get things moving if they could just point me to a website that
simply says "Here's the places we cover". (although ideally it would be
something I could grab from within the WRLD API, however i understand thats
probably a low priority for them right now.)


Basically, the game I made is in a way a (perhaps not all that effective)
marketing vehicle for them -- all it really does is show off the art they
have put into their map of the world. So I'm saying, to the artists: "Where
can I see a list of places you're really proud of that you'd most want
people to see from a VR hot air balloon? (or just point me to a complete
list of coverage and i'll build it myself)"

Gabriel

**Comment by AubreyF** [comment]
Ah, sweet! Here's the site :)

https://www.wrld3d.com/3d-maps/mapping-data/#WRLD-MAP-COVERAGE

**Comment by GabrielBakker** [comment]
Thank you. They got anything like a List of Places?

Its just that the world map is not terribly specific.

For example, imagine you are looking for beautiful places to show in
Brazil. Brazil is a huge place -- the map you just pointed me to says
"Partial Coverage". The only way i've found so far to check WHICH parts of
Brazil have coverage is to load their demo scene and scroll around. But
that doesn't work very well either because you can't see if there's
coverage at low zoom levels until you zoom all the way in there.

Brazil, which is almost as big as the continent of Australia, and has
beautiful mountains, a river wider then Switzerland, and the Amazon
Rainforest, loads of places people would want to see. Not to mention
Australia, which is also marked "Partial Coverage".

Just saying Brazil has partial coverage, doesn't help much if the only tool
to find out which coverage is to then zoom around slowly past endless miles
of ocean checking for a bit of land.

So is there an easier way? A list of places they'd like to show off perhaps?


Guessing and poking about their map randomly has led me to a small list of
16 or 20 places that people can fly over in a Balloon. But why poke about
when whoever is actually making the art probably would be happy to tell me
which places they want to show off the most!


I do appreciate all your help so far Aubrey. I'm pretty curious about your
game as well. It sounds a lot more ambitious then what I was working on,
really just a hobby for me. But I'd love to check it out sometime if you
like.

Gabriel

**Comment by AubreyF** [comment]
@GabrielBakker I am not aware of any more specific lists of places, but I would be delighted if someone from @wrld-teamcity could chime in here.

The project I am working on incorporates several different mapping technologies. So far, WRLD is the most beautiful solution I have found for providing large-scale interactive cities - but also the least performant. The "special places" list I have been building uses WRLD for perhaps 25% of destinations, and other satellite-terrain libs for coverage of the rest of the planet. My game is also a single-person hobby, at this point. I've produced 16 or so preview releases so far this year. The next preview is a few weeks out, but it is the one which will introduce the real-world terrain environments. Feel free to check it out! https://terra.vision.

**Comment by GabrielBakker** [comment]
Woah that is really cool, and beautiful. I'm interested to know some of the
other technologies you're using for some of the other places too, but its
probably off topic to discuss here.

Add me on Facebook if you like, I'd love to continue this discussion! My
name is "Gabriel Bakker" on there too.

Gabriel

**Comment by jlunderwood** [comment]
Just to add a bit more information to the page you found at https://www.wrld3d.com/3d-maps/mapping-data/#WRLD-MAP-COVERAGE for the areas marked "Partial coverage".

For our Unity SDK, the cities in the "partial coverage" areas are:

- Spain: Barcelona
- France: Paris
- Germany: Bremerhaven
- Brazil: Rio de Janiero, Sao Paulo
- Australia: Melbourne
- Thailand: Bangkok  

  
Our WRLD mobile app includes direct navigation to the following cities:
Bangkok, Chicago, Dundee, Edinburgh, London, Milan, New York, Oslo, Rio, San Francisco, Vancouver
Many other major cities in the countries covered have had some degree of art customization for landmarks.

**Comment by jonty-dawson** [comment]
Closing this as feature request is covered by #49
