### ISSUE TITLE
Custom Namespace ?

### ISSUE THREAD

**Issue by MosheBenZacharia** [wrld3d/unity-api#56]
Hey,

Why is there no WRLD namespace? It's best practice in Unity/C# for all scripts from custom packages to have their own namespace.

-Mo

**Comment by johnbell84** [comment]
Hi MosheBenZacharia,

Thanks for trying our maps!

We try to keep our C# code under a Wrld namespace, but you're quite right that there are a few places where this has been missed.  This is something we'll try to improve on in future releases.

Kind regards,

John
