### ISSUE TITLE
Disable billboard signs

### ISSUE THREAD

**Issue by yosun** [wrld3d/unity-api#58]
Is there a way to disable unwanted "layers" such as the billboard signs? There seem to be these billboard signs that are not correct https://gyazo.com/972a498138cb16f13c12251fec5cdf6a

**Comment by tim-jenks** [comment]
@yosun the billboards you see are actually a 'landmark' - you will be able to find them within the Unity Scene Graph.

At the moment there is no way to opt out of these, other than disabling them yourself in the scene graph.

I am closing this issue for now - please reopen if this is insufficient.

**Comment by yosun** [comment]
Ah so that requires a hierarchy search each time it's loaded? Quite inefficient? 

Is there a way to disable other layers other than searching through the scene graph?

**Comment by tim-jenks** [comment]
#62 should provide you the eventful approach - again as a work around in the mean time you can traverse the scene hierarchy O(N) ? and N is very small from our side.
