### ISSUE TITLE
Adding components to each mesh/render object

### ISSUE THREAD

**Issue by yosun** [wrld3d/unity-api#62]
What's the best way to "subscribe" to when new map objects are added, for the purposes of adding components to each one?

**Comment by tim-jenks** [comment]
@yosun this is not simple at the moment, I have added this as a desired feature and accepted it on the roadmap.

I propose we add an extension to the WRLD API that fires a callback when one of our map entities are added to the scene graph. 

There may be a way to observe the Unity Scene Graph and do this yourself in the meantime.

**Comment by yosun** [comment]
Traversing the unity scene graph is not performant, so ideally there would be some sort of callback for when data like this is received/processed.

**Comment by tim-jenks** [comment]
Agree - proposed as a workaround until we make the feature enhancement for you

**Comment by ghost** [comment]
No current plan to implement this.
