### ISSUE TITLE
Prevent default camera when pointer is over UI 

### ISSUE THREAD

**Issue by yosun** [wrld3d/unity-api#64]
Is there a way to prevent the default wrld camera from responding when a user touches/clicks a UI layer element?  

Or, where should if (EventSystem.current.IsPointerOverGameObject(0)) return; go?

**Comment by jonty-dawson** [comment]
Thanks for bringing this to our attention - currently there isn't an elegant way of preventing the WRLD camera from consuming all input.
As a short-term work-around, you may be able to locally modify a script in the distributed WRLD SDK:
in
./Assets/Wrld/Scripts/Camera/CameraInputHandler.cs
At the top of method UpdateInputFrame(), add the condition that you suggest, eg:
        void UpdateInputFrame()
        {
            if (UnityEngine.EventSystems.EventSystem.current.IsPointerOverGameObject())
            {
                return;
            }
            //....

We'll attempt to fix in a more extensible way.

**Comment by yosun** [comment]
It seems that the camera still moves though input starts above the UI...

**Comment by yosun** [comment]
Actually is there a way to override the map camera controls completely? (And also reactivate it at runtime later)

**Comment by yosun** [comment]
Just checking if this has been fixed yet? 

Would like to release a version of my app with this fix soon...

**Comment by jonty-dawson** [comment]
Tracking internally: MPLY-9542

**Comment by jonty-dawson** [comment]
Not resolved in v0.6

**Comment by jbrownwrld** [comment]
Hello, 
This issue has been fixed as of v0.6; you may now supply a boolean delegate to the `CameraApi` to manage when to apply the built-in camera controls to the controlled camera. This is done with the `CameraApi.RegisterShouldConsumeInputDelegate` in [CameraApi](https://wrld3d.com/unity/latest/docs/types/Wrld.MapCamera.CameraApi/).
Our examples now use this functionality to disable the camera movement when the cursor is over UI elements.
To disable them entirely, you can use a simple function that always returns false.
