### ISSUE TITLE
Path navigation along roads

### ISSUE THREAD

**Issue by yosun** [wrld3d/unity-api#65]
Is there a way to discern where the road endpoints are (i.e., where the next street or even just the intersections are) in order to navigate (walking) characters "on" the map?

**Comment by jonty-dawson** [comment]
Currently, there is no navigation graph of roads exposed in the WRLD Unity api. It probably isn't practical to attempt to infer this from the road geometry resources in Unity as these are triangle Meshes without structural information about individual roads or junctions.
We hope to add some form of navigation feature to the Api in the future, but do not have a milestone for this yet.

**Comment by jonty-dawson** [comment]
See also discussion on https://github.com/wrld3d/unity-api/issues/52

**Comment by ghost** [comment]
Transport network is now available in SDK v0.8: https://www.wrld3d.com/unity/latest/docs/examples/access-network-using-transportgraph/
