### ISSUE TITLE
Highlighting buildings "too fast" seems to lead to a BuildingsAPI dictionary failure

### ISSUE THREAD

**Issue by yosun** [wrld3d/unity-api#66]
temporarily fixed by setting private to public static Dictionary<int, HighlightRequest> HighlightRequests; and checking for BuildingsApi.HighlightRequests.ContainsKey(lastHighlighted.HighlightId)

since the callback seems stochastical when buildings are highlighted too fast, you may want to check for existence before calling it

[![https://gyazo.com/7958a4cc12e570263a1ba5e6f8b035ea](https://i.gyazo.com/7958a4cc12e570263a1ba5e6f8b035ea.jpg)](https://gyazo.com/7958a4cc12e570263a1ba5e6f8b035ea)

**Comment by yosun** [comment]
if(HighlightRequests.ContainsKey(highlightRequestId)){ 
                var request = HighlightRequests[highlightRequestId];
                HighlightIdsToAdd.Add(highlightMeshId);
                var gameObject = HighlightStreamer.GetObjects(highlightMeshId)[0];
                gameObject.GetComponent<MeshRenderer>().sharedMaterial = request.material;
            }

BuildingsAPI.cs line 267ff 

That's my fix for now - not sure if that might break other Wrld features...

**Comment by tim-jenks** [comment]
Accepting this as a known bug - will fix for next release

**Comment by jonty-dawson** [comment]
Fixed on v0.6, but involves api change - migration notes to follow

**Comment by jonty-dawson** [comment]
See snapshot docs:
https://docs.wrld3d.com/unity-SNAPSHOT/latest/docs/examples/highlighting-buildings/
Migration notes on:
https://docs.wrld3d.com/unity-SNAPSHOT/latest/docs/examples/whats-new-unity-sdk-0.6/

**Comment by jonty-dawson** [comment]
Snapshot package available here:
https://eegeo-static.s3.amazonaws.com/unity/wrld.unity.sdk-SNAPSHOT.zip
