### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by AubreyF** [wrld3d/unity-api#67]
I am currently experiencing "Unsupported platform StandaloneLinuxUniversal" errors when attempting to build my project with a Linux target.

Are there any plans to support Linux builds? For my project, this is a much higher priority than WebGL (#60) 

Edit: Even if WRLD has no short-term plans to support Linux builds, it would be better to use platform-dependant compilation than to break all builds for nonsupported target platforms. https://docs.unity3d.com/Manual/PlatformDependentCompilation.html

**Comment by Michael-ODonnell** [comment]
Hi Aubrey

Linux support isn't on our roadmap for the near future I'm afraid but I've flagged this as a feature request and will raise it with the team to see what it would take.  It's also too late in our development cycle for it to be included in the next release, so it would be the release after that at the earliest.

Regards,
    Micky.

**Comment by AubreyF** [comment]
Hi Micky, thanks for the insight. I'll experiment with platform dependent compilation of the WRLD codebase in my project for the immediate future.

**Comment by jonty-dawson** [comment]
Closing as dup of #43 - still no planned milestone for this feature request
