### ISSUE TITLE
Get API Key not working

### ISSUE THREAD

**Issue by maxmills372** [wrld3d/unity-api#68]
I have created an account and when I go to the developer portal to request an API key, it tells me to log in (even though I already have) and then takes me to the home page. Its an endless loop and I cannot get a key.

**Comment by Tezirg-Wrld3D** [comment]
Hello maxmills372,
Thank you for reporting, we will fill in a new bug ticket to solve this issue. 

Meanwhile, can you try to logout, restart your browser and login again?

**Comment by jonty-dawson** [comment]
Closing, issue on accounts page now fixed.
See also #39 for general API key support
