### ISSUE TITLE
LOD Selection - Using WRLD with VR

### ISSUE THREAD

**Issue by GabrielBakker** [wrld3d/unity-api#7]
I notice in your demo scenes, when I fly around the world its fast and smooth and it lets me zoom out all the way to space without a problem. (It just fails to load at intermediate elevations).

When I try to fly to space in my game, as the elevation increases it quickly reaches a point where the edges of the map can be seen and the game gets very choppy. Is there a way to control the LOD so that in my VR game I can smoothly fly from the surface out to space? How did you achieve this in the demo?

I attempted to place my VR camera object and VR vehicle in your demo scene and tie your main camera to my VR camera and disable it the way I got things working before - in your demo scene configured with my VR component, whenever the game is running I see no map. As soon as I push the Pause button, the map shows up exactly how it should be. When I push play again, the map disappears. Have you run into behavior like that before? (Your demo scene works fine if I don't put the SteamVR plugin in it.)

**Comment by Pirh** [comment]
Hi there,

The LOD displayed by the map is fully determined by the Camera used for streaming. So when the camera is at high altitudes, lower levels of detail are used for the terrain and buildings. There is currently no way to manually control this.

As for the demos (I assume you mean the scenes packaged with the SDK?) the streaming works the exact same way. Without seeing your game's project, I'm not sure why it would be choppier.

Finally, I haven't encountered any issues where the map would only display when paused. Is there any console output to suggest any errors? Failing that, try to determine whether the map is failing to render, or whether it is out of your camera's view. (Check your camera's position in Pause/Play mode, attach some debug rendering to the map tiles, etc.)

**Comment by GabrielBakker** [comment]
Thank you for getting back to me. The issue where the map would only stream
when paused turned out to be something else: the map only streams when my
app has the focus. But in VR its easy for something else to have focus
while you're still playing. Pausing my game was also setting focus back on
my game.

The issue with altitude is understandable but not super consistent..
sometimes I have a lower res at a lower altitude. Sometimes it's better
from farther away.

But the only real issues I still have are these:
If the camera turns away from the map those parts of the map are unloaded
immediately. If the camera turns back they have to be reloaded. When you're
in VR, you move your head around constantly and look in different
directions. This means the map pieces are constantly unloading and loading
and it looks goofy, makes the world look fake, takes you out of the
experience and keeps the cpu busy doing needless work. It would work a lot
better if the pieces waited until they were out of view for 15 seconds
before going away.

Finally, in the demos you can go from right on the ground and zoom all the
way out until you see the whole world and its just a little ball on the
screen. I'm my game when the elevation of the camera gets high enough only
around 5000 meters, my game crashes and the api gives an error, something
about invalid elevation for streaming. In the demos how are you able to
allow the camera to zoom out all the way to space?

Gabriel

**Comment by Pirh** [comment]
Hi Gabriel,

At the moment, it is intentional that only tiles in the view frustum of your streaming camera be loaded in at any time. However, your streaming camera and the camera that is rendering don't have to be the same. If you want to stream in map data that is not in view of your player, you can create a camera positioned behind them, or above them, such that more tiles are in view. Then set this new camera to the **Camera** field of your WrldMap component.

Given that this is probably a common requirement for VR, we may look into more flexible ways of streaming in map data. Thanks for all of your feedback so far, it really is invaluable in helping us to find what's missing from our SDK.

As for your other issue - the crash at high altitudes - I haven't seen this bug before. Could you create another GitHub issue containing the error messages you're seeing? We can try to work out what's going wrong from there.

Thanks,
Paul

**Comment by GabrielBakker** [comment]
Yes, I'm creating new GitHub issues for these two complaints now :) sorry,
I realized i should have done that after I listed the problems here.

That is a good idea regarding moving the camera to behind the player. I am
going to play around with it and see what I can achieve.

**Comment by Pirh** [comment]
Linking in those two new issues: #16 and #17 and closing for now.
