### ISSUE TITLE
Masking parts of map

### ISSUE THREAD

**Issue by saadminhas** [wrld3d/unity-api#71]
Hi,

Is it possible to mask/remove part of the streamed map? so that we can add our own Gameobject environment models within the masked area?

Best Regards,
Saad

**Comment by johnbell84** [comment]
Hi Saad,

Thanks for your interest in our maps!

We've had a few requests for API-level functionality to replace specific map tiles, so I suspect this is something we'll look at making easier in future.  At the moment, however, I'm afraid I don't think I can suggest a more elegant solution than looking for the names of the offending GameObjects and programatically replacing them.

I hope this helps.  Best of luck with your project.

**Comment by ghost** [comment]
There isn't an API to do this, however this example script can be used to disable any buildings within a given Morton Key: 
[Scripts.zip](https://github.com/wrld3d/unity-api/files/5750377/Scripts.zip)
