### ISSUE TITLE
WRLD sdk and ARkit - Zoom pan is not working

### ISSUE THREAD

**Issue by Vinita18** [wrld3d/unity-api#73]
I am following this tutorial https://www.wrld3d.com/blog/use-arkit-wrld-unity-sdk-part-1/ given here for ARkit but the zoom, pan control is not working. I am using built in camera controls here.

there are 2 cameras is scene one is StreamingCamera and other is MainCamera where ARkit scripts are added. please help me with this.

Also WRLD map is not matching with horizontal plane.

**Comment by ArslanJafri** [comment]
Hi Vinita,

Thank you for your interest in WRLD Unity SDK and checking out the ARKit tutorials. Built in controls do not work with ARKit as you have discovered, however it's not too hard to implement a custom pan gesture using [Wrld.Api.Instance.SetOriginPoint](https://wrld3d.com/unity/latest/docs/types/Wrld.Api/). 

As for the Map not matching horizontal plane, if you mean that maps are going out of bounds of the detected planes then you need to create a mask to limit them. Instructions for them can be found in [part 2](https://www.wrld3d.com/blog/using-arkit-wrld-sdk-part-2/) of the tutorial series.

Hope you find this helpful, but please get in touch if you have further questions.
 
Kind regards,

Ali Arslan

**Comment by jonty-dawson** [comment]
Closing this as suggestion seems to mitigate
