### ISSUE TITLE
UnityWorldSpace scene has gitter if both Camera Controllers are active and you move with Right Mouse button

### ISSUE THREAD

**Issue by clearbrian** [wrld3d/unity-api#8]
Unity 5.6.1f1
mac OS Sierra 10.12.5 (16F73)
WRLD sample from unity store
Run UnitySampleSceen
Pres PLAY
Right click with Mac mouse - serious gittering

http://appjoyride.com/unitybug/UnityScreenSnapz001.mov

movie recording has some dropped frames but gitter still  serious.
Built standalone version of mac app and still occurs.

**Comment by tim-jenks** [comment]
@clearbrian - could you confirm which Scene you are using and your inspector settings?

If you are using Scenes / UnityWorldSpace - the behaviour you are showing in the video looks like you have two cameras fighting.

Could you confirm whether the WrldMap game object has it's 'Use Built-in Camera Controls checked' ?

If it does, could you also confirm that the debug Fly Camera Behaviour script is disabled?

**Comment by clearbrian** [comment]
that was the issue. Thanks. 
Think this is more a noob onboarding/ux issue. 
When you first run the demo. CLICK and drag with Left mouse does nothing so I hunted around and found check box and drag started to work.
Then later right clicked and dragged and got that gitter so thought it was a bug.
So you can either DRAG or Lookaround. If you try and enable both you get the gitter.
So two ways to improve the example code
if 'Use Built-in Camera Controls' unchecked 
- LEFT CLICK does nothing
- need to prompt user to RIGHT CLICK to look around
- need a script to allow them to drag if 'Use Built-in Camera Controls' unchecked 

if 'Use Built-in Camera Controls' checked 
- LEFT CLICK drags the map.
- RIGHT CLICK - causes gitter
- need to disable the script clashing with the default camera controls

cheers

**Comment by tim-jenks** [comment]
It's our bad, the UnityWorldSpace scene has two camera controllers, our stock camera controller or a 'debug' WASD 'Fly' camera controller.

The use of one or the other is not mutually exclusive currently so you need to do some script disabling. We'll improve this in a future release.

**Comment by malcolm-brown** [comment]
We removed the FlyCameraBehaviour example 'custom' camera controller due to the issues described here with how the example was set up. Custom camera controllers are still supported and [explained here](https://wrld3d.com/unity/latest/docs/examples/using-your-own-camera-controls/).
