### ISSUE TITLE
Add confirmation that entry to indoor map has succeeded or failed

### ISSUE THREAD

**Issue by jonty-dawson** [wrld3d/unity-api#80]
IndoorMapsApi.EnterIndoorMap does not have return value or delegate to be notified of success/fail response.
Hooking to IndoorMapsApi.OnIndoorMapEntered  is insufficient - need to rely on arbitrary timeout to assume failure if this event is not subsequently fired.

**Comment by ghost** [comment]
Tracking internally: WRLD-331
