### ISSUE TITLE
How do I add ARCore Support to my existing WRLD3D Project?

### ISSUE THREAD

**Issue by dellams** [wrld3d/unity-api#81]
Hi there,

How do I add ARCore Support to my existing WRLD3D Project?

I see your demo project, but I have an existing project and wanted to know how to add ARCore support to it?

Many thanks,
David.

**Comment by dellams** [comment]
Also, your sample ARCore project does not work for me. In your steps here:

https://wrld3d.com/unity/latest/docs/examples/device-deployment-arcore/

You state on step 10 that you can set the API Key on the WrldMap GameObject, however when I select it there is no API Key box in the inspector as I have shown in the attached screenshot.

"10. Select the WrldMap GameObject inside Wrld Map Parent and paste your API Key, obtained from step 7, into the field shown in the Inspector"

<img width="1680" alt="screen shot 2018-04-27 at 13 20 22" src="https://user-images.githubusercontent.com/3522378/39346147-39da43be-4a1f-11e8-923c-afecc016767a.png">

Also, on step 9, I did not receive any prompt asking me to setup the scene. I also could not find any ARCoreSetupHelper file. Why did I not get the prompt? And where is this file? Thank you.

Many thanks,
David.

**Comment by ArslanJafri** [comment]
Hi David,

Setting up the ARCore project is required before API Key can be set in WrldMap. If you did not get the prompt, then you can easily select the ARCoreSetupHelper gameObject from the scene hierarchy and click the Setup ARCore button from there. Please see the attached image for reference. 

![setup popup](https://user-images.githubusercontent.com/16162390/39367217-08be8b64-4a2e-11e8-98f1-ffa1a2c5efc5.png)

As for integrating with an existing project. Once you get the samples working, you should be able to copy the assets to your project and integrate with your work from there. You will also need to make sure that the project settings match the ARCore sample project to ensure that it builds and functions correctly.

Best,

Ali

**Comment by dellams** [comment]
Ok thanks, I sorted that but when I run it I just get a white screen in the Unity Editor, is that normal?

The normal WRLD3D loads the 3D maps...

Regarding getting it working with my existing project, I was hoping for a more detailed complete step by step instructions on how to set up the ARCore with your SDK. 

That way nothing will be accidentally missed.

Would be really appreciated.

Many thanks,
David.

**Comment by dellams** [comment]
Also when I build and run it for Mac I also get a white screen.

**Comment by ArslanJafri** [comment]
The white screen is expected in Unity Editor if there is no ARCore compatible device available with the InstantPreview App installed. You should get a message instructing you to install InstantPreview in the Unity console on the latest ARCore SDK. If you are getting an error in the console about missing Android SDK, then you should check if the path for the Android SDK is correctly set in Unity Editor's settings.

The ARCore samples are intended to run on on an [ARCore supported device](https://developers.google.com/ar/discover/#supported_devices) so they will not correctly deploy on any other platforms. Please create a build for Android and run it on a supported device.

At the moment we do not have a step by step guide available for ARCore. We have a step by step guide for [ARKit](https://www.wrld3d.com/blog/use-arkit-wrld-unity-sdk-part-1/) which in functionality is very similar to ARCore. It is slightly out of date but it should give you a rough idea on how our AR Samples are configured. We might publish a step by step guide for ARCore but at the moment it is not scheduled.

Hope you find this helpful, please feel free to get in touch if you have any further questions.

Best,

Ali

**Comment by ghost** [comment]
AR support has been revised in SDK v0.8 to use Unity AR Foundation. See https://www.wrld3d.com/unity/latest/docs/examples/device-deployment-xr/ for updated example project.
