### ISSUE TITLE
Search indoor map

### ISSUE THREAD

**Issue by MephestoKhaan** [wrld3d/unity-api#83]
It seems the only way to get an indoor map geometry is by calling the `Enter` function. But that comes with its own animations etc. 

I would like to have a bit more of control over that. is there any callback (or any plan to do it) so I can get just the gameobjects and a nice way to access them? Right now the only choice seems to be to search under the Indoors gameobject manually with the Indoor_ID_Floor_X thing.

**Comment by marksimpson82** [comment]
Hi MephestoKhaan,

You're correct in that the current API does not directly expose the Unity GameObjects for indoor maps, and the Api controls the indoor animations. I agree that it'd be useful for developers to have access to the Unity GameObjects via the indoor maps API & and more control over animations. While I can't guarantee we'll implement these changes in the near future, we'll bear it in mind when working on future revisions of our indoor maps API.

Best regards,
Mark

**Comment by MephestoKhaan** [comment]
Thanks! I hope you can add it at some point.
Just fyi on the mean time I created my own data structure, being populated with callbacks added to your 
`IndoorMapScene.AddRenderableInternal` method.

It seems this method fires when I receive interiors, but where is the one for when they are removed? (I guess I could just plug to their `OnDestroy` tho...
