### ISSUE TITLE
API Key empty on Android.

### ISSUE THREAD

**Issue by RedYggdrasil** [wrld3d/unity-api#86]
Hi, I encounter what seam to be a bug in the plugin while building on Android, the maps where not appearing and the log say I have no key.

The plugin work correctly in the editor, I entered the key in the component, the map load itself in editor, I saved the map, restarted unity but still no key on Build, it look like the key is not passed in the build version.

Device : Samsung S8
Unity : 2018.1.1f1
Plugin version snapshot to fix shader problem : http://cdn1.wrld3d.com/unity/wrld.unity.sdk-SNAPSHOT.zip

![screenshot_20180525-171602_carte de visite](https://user-images.githubusercontent.com/15359127/40554039-c7292c72-6044-11e8-84ce-7b60cd5b8086.jpg)

**Comment by tommymacdonald** [comment]
Hi,

This is a bug we have tracked internally. The Examples scene included in our SDK features multiple WrldMap components - after adding an API key to one WrldMap component, the key should be present across other WrldMap components, but is currently only functioning correctly when running the scene in-editor.

The current workaround is to select each GameObject with a WrldMap script attached in the hierarchy in the Unity editor; this should cache the API key correctly in all of them. If you then save your scene and re-build to your device, you should not encounter this issue.

Apologies for the inconvenience, and please let us know if you encounter any further issues.

Kind regards,
Thomas

**Comment by ghost** [comment]
This is fixed in the v0.8 SDK release
