### ISSUE TITLE
Question: Flaten the world

### ISSUE THREAD

**Issue by MateiGiurgiu** [wrld3d/unity-api#87]
Hi, I am wondering if there are any plans for adding flat world streaming. I have spatial data only as lat and lon without altitude, and is very hard to correctly place objects. I have seen your example from indoor building where you flatten the terrain and building by scaling them down, but I would like to keep the buildings as they are.

Thank you!

**Comment by jonty-dawson** [comment]
The Positioner class is intended to help with positioning objects at a lat-lng location, and optionally a height relative to the terrain at that location.
See: https://wrld3d.com/unity/latest/docs/types/Wrld.Space.Positioners.Positioner/
And an example:
https://wrld3d.com/unity/latest/docs/examples/fly-object-over-map/

For the forthcoming v0.7 release, we have made some improvements to Positioners, and added additional examples - we expect this to be available on Asset Store within the next few weeks.

**Comment by MateiGiurgiu** [comment]
Thank you. I need to convert a lot of LatLon point to their Unity World position, but I don't see any API in the Positioner class for getting the Unity World position, there is only a TryGetECEFLocation method.

Are there any plans for the future to include an API to directly convert a LatLon point to its Unity World space corespondent?

**Comment by jbrownwrld** [comment]
Hello there, 
The changes coming in the v0.7 release for the Positioner class will provide a way to do this. 
Until then, you should be able to use `CameraApi.GeographicToWorldPoint(LatLongAltitude, Camera)`;
see https://wrld3d.com/unity/latest/docs/types/Wrld.MapCamera.CameraApi/ .

**Comment by jonty-dawson** [comment]
Closing during sweep
You can use a Positioner to place objects at a height relative to the terrain at a given lat-lon coordiate.
https://wrld3d.com/unity/latest/docs/types/Wrld.Space.Positioners.PositionerApi/
See example here:
https://wrld3d.com/unity/latest/docs/examples/position-object-with-positioner/
