### ISSUE TITLE
Places Availables

### ISSUE THREAD

**Issue by enriqif** [wrld3d/unity-api#89]
### Description
I want to create a map of my city.. but isn't available in this coordinates, I just can saw water. 

### Additional Information
This are my coordinates

Latitude: -24.121222
Longitude: -64.202511
url: https://wrld.mp/52dbf98
Unity 2018.1.0.f2

**Comment by Michael-ODonnell** [comment]
Hi Enrique,

Unfortunately we don't have data coverage for Argentina yet.  Ultimately our goal is to have full coverage of Earth but we tend to prioritize which areas we focus on next based on business leads and user feedback.  If you register an account with us on our website then you can vote for Argentina at https://www.wrld3d.com/3d-maps/mapping-data/#WRLD-MAP-COVERAGE to move it up the priority list.  This will also let you see where it currently stands in the voting. 

We can also expedite work based on commercial agreements - please get in touch with our sales team at enquiries@wrld3d.com if this applies.

**Comment by enriqif** [comment]
Thank you so much for you reply!!

I send my vote and I hope that your team can add Argentina soon!!
