### ISSUE TITLE
Creating any map other than San Fran [Question]

### ISSUE THREAD

**Issue by NeoCroMagnon** [wrld3d/unity-api#9]
Sorry, this might be a silly question but, i'm trying to export the data from wrld3d for London to build it in Unity and I just seem to be able to build San Fran, I'm sure there's something very silly I'm missing but i can't seen to find an intro tutorial on how to to do that. Any tips? Thanks

**Comment by NeoCroMagnon** [comment]
Just to clarify, I'm creating new API keys on the site, on the map builder, but when I paste them inside of Unity, it doesn't seem to matter, when I press play, it just loads San Fran again.

**Comment by tim-jenks** [comment]
Hi @NeoCroMagnon.

When opening 'EcefSpace' or 'UnityWorldSpace' scene, please see the Unity Inspector:

Camera/View Settings
Camera => Main Camera
Use Built-in Camera Controls => Check (unless you want to provide your own camera)
**Start Latitude => Sett to your starting latitude
Start Longitude => Set to your starting longitude**

Additionally, you can control the camera in code, please take a look at the C# examples here if you are using our built in camera: https://www.wrld3d.com/unity/latest/docs/examples/moving-the-camera/

The WRLD Unity SDK uses WGS84 lat,lons like most other mapping providers, so if you enter a lat,lon for London the WRLD SDK will stream the view around that area.

You can use our web maps to find lat,lons: https://maps.wrld3d.com/ 
If you navigate to a location -> right click -> select what's here you can copy the coordinates.

I'll close the issue as this is relatively straight forward, if you need additional help please post back and we'll respond.
