### ISSUE TITLE
Examples root directory does not contain a "welcome" or "table of contents"

### ISSUE THREAD

**Issue by Draco18s** [wrld3d/unity-api#90]
Instead it displays the first example in its body contents.
https://www.wrld3d.com/unity/latest/docs/examples/

This, combined with the list of examples sidebar looking so much like the API sidebar that it's invisible, makes the examples link look like there is exactly 1 example.

This is awful site design.

**Comment by johnbell84** [comment]
Hi Draco18s,

Thanks for the feedback, it's really useful to hear where we could make things clearer.  We'll make our design team aware of this.

Kind regards,

John
