### ISSUE TITLE
Possible to have a sample project which implements both ARCore & ARKit?

### ISSUE THREAD

**Issue by dellams** [wrld3d/unity-api#93]
Hi there,

We see you have your sample project for both ARCore & ARKit but they are currently both separate.

Would it please be possible if you can supply a sample project which merges these two together?

We have held off using your awesome SDK for a while waiting for your Unity implementation because we did not want to manage two separate codebases for both Android and iOS but now with AR they have been separated again, so it would be great if they could be merged please?

Many thanks,
David.

**Comment by ArslanJafri** [comment]
Hi David,

While we have not tried it, it shouldn't be too hard to merge the two projects together. Some helpful steps are given below. Please let us know if you face any issues and we will try to help out.

1. Start with any sample projects. Let's say ARKit.
2. Copy the [Common](https://github.com/wrld3d/wrld-unity-ar-samples/tree/master/Common) folder to [Wrld Sdk Samples](https://github.com/wrld3d/wrld-unity-ar-samples/tree/master/ARKitSample/Assets/Wrld%20SDK%20Samples).
3. Copy the [ARCore Sample](https://github.com/wrld3d/wrld-unity-ar-samples/tree/master/ARCoreSample/Assets/Wrld%20SDK%20Samples/ARCore%20Sample) folder from the ARCore Sample Project to [Wrld Sdk Samples](https://github.com/wrld3d/wrld-unity-ar-samples/tree/master/ARKitSample/Assets/Wrld%20SDK%20Samples).
4. Follow the given setup steps for both [ARKit](https://wrld3d.com/unity/latest/docs/examples/device-deployment-arkit/) and [ARCore](https://wrld3d.com/unity/latest/docs/examples/device-deployment-arcore/) from step 5 and onward on the merged project.
5. Make sure that builds settings are correct for both platforms. For example, [ARCore needs these settings](https://developers.google.com/ar/develop/unity/quickstart-android#configure_build_settings).
6. Switch to the required platform and build.

You might also be interested in the iOS setup for ARCore which provides an integration with ARKit. If you want, then you can just use the ARCore sample and deploy it to both Android and iOS. See the steps on the ARCore documentation for deploying to to iOS and Android. It might simplify the process for you if you do not have to merge the samples.
ARCore Android: https://developers.google.com/ar/develop/unity/quickstart-android
ARCore iOS: https://developers.google.com/ar/develop/unity/quickstart-ios

Best,
Ali

**Comment by ghost** [comment]
Updated sample project for XR Foundation and Unity 2019/2020: https://github.com/wrld3d/wrld-unity-xr-samples/
