### ISSUE TITLE
WRLD Unity SDK is no longer available on the Unity Asset Store

### ISSUE THREAD

**Issue by datascape** [wrld3d/unity-api#94]
### Description

The asset store page now says: Unfortunately, WRLD Unity SDK is no longer available.

### Steps to Reproduce

Click link on the folllowin page. Please update this page:

https://github.com/wrld3d/unity-api/milestone/2

Asset store no longer allows WRLD to be downloaded:

https://assetstore.unity.com/packages/tools/modeling/wrld-unity-sdk-86284

**Comment by tommymacdonald** [comment]
Hi,

Thanks for your interest in our maps! We are currently investigating this, but in the meantime please download the Unity SDK from [this docs page](https://wrld3d.com/unity/latest/docs/api/).

Kind regards,
Thomas

**Comment by datascape** [comment]
Hi Thomas, I have a couple questions about the package import process.

When following the steps on the WRLD import link:
https://docs.unity3d.com/Manual/AssetPackages.html#ImportingPackages

Choosing "Assets > Import Package" only shows the "Custom Package" option.

When I attempt to import WRLD from the unzipped file, I see 569 subfolders with GUIDs for folder names. None of these are importable.

What are the steps to upgrade my local WRLD asset package in Unity, and how do I tell the version of my current package?

**Comment by tommymacdonald** [comment]
Hi,

If you unzip the package linked on the docs page, you should have a .unitypackage file. This can be imported into Unity using the Assets → Import Package → Custom package... dialog.

If you are on macOS and using the default unzipper, it may have automatically unzipped the .unitypackage. To avoid this, you can manually run the following command in a terminal window:

`unzip wrld.unity.sdk.0.7.1019.release.zip`

You can check your current version of the WRLD SDK by opening your project in Unity and navigating to Assets → WRLD → Version. There will be a text file which matches the version of the SDK you are currently using.

Kind regards,
Thomas

**Comment by Shizola** [comment]
Is there any update on why it was removed?  I used WLRD a while ago but assumed the company had gone out of business or something. Also worth nothing that without the asset store new developers may never discover it and go with a different solution. If you google "unity map plugin", wrld only appears half way down the second page.

**Comment by jonty-dawson** [comment]
Hi - thanks for the question. We expect to be able to distribute the WRLD SDK via Unity asset store in the near future. Meanwhile, the SDK can be downloaded from:
http://cdn1.eegeo.com/unity/wrld.unity.sdk.0.7.1019.release.unitypackage

See "Getting Started..." here:
https://wrld3d.com/unity/latest/docs/examples/
