### ISSUE TITLE
NativePrecacheApi_GetMaximumPrecacheRadius errpr

### ISSUE THREAD

**Issue by MephestoKhaan** [wrld3d/unity-api#96]
Suddenly I can't run even the demos because the next error triggers when starting Wrldmap:
`EntryPointNotFoundException: NativePrecacheApi_GetMaximumPrecacheRadius
Wrld.Precaching.PrecacheApiInternal.GetMaximumPrecacheRadius` every time.

It was working yesterday and nothing seems to have changed.

**Comment by MephestoKhaan** [comment]
NEvermind it is probably an error on my side after updating to 0.7 and moving branches. any pointer towards where to look at a possible fix would be greatly appreaciated

**Comment by ghost** [comment]
Closing out old/stale issues.  Please re-open if this still reproduces.
