### ISSUE TITLE
CameraApi should support indoor maps

### ISSUE THREAD

**Issue by jonty-dawson** [wrld3d/unity-api#97]
CameraApi.MoveTo, CameraApi.AnimateTo etc should be able to specify a target point on an indoor map, in a similar manner to WRLD Android + iOS SDKs.

For example:
https://wrld3d.com/android/latest/docs/examples/move-the-camera-to-an-indoor-map/
https://wrld3d.com/android/latest/docs/examples/animate-the-camera-to-an-indoor-map/
https://github.com/wrld3d/android-api/blob/master/sdk/src/main/java/com/eegeo/mapapi/EegeoMap.java#L171

**Comment by ghost** [comment]
Tracked internally: WRLD-332
