### ISSUE TITLE
Add api to perform map feature picking

### ISSUE THREAD

**Issue by jonty-dawson** [wrld3d/unity-api#98]
It would be desirable to be able to perform raycast against map features, similar to Android api. See docs here:
https://docs.wrld3d.com/android/latest/docs/api/EegeoMap/
pickFeatureAtScreenPoint
pickFeatureAtLatLng

And api implementation:
https://github.com/wrld3d/android-api/blob/9f2d4cdc23a245a93ca6e32b6bb1cb19c32ca4d6/sdk/src/main/java/com/eegeo/mapapi/EegeoMap.java#L755

**Comment by ghost** [comment]
Tracked internally: WRLD-333
